const fs = require('fs');

const extraVotka = `  {
    id: 'absolut',
    name: 'Absolut',
    emoji: '🧊',
    color: '#004890',
    aliases: ['Absolut Blue'],
    origin: 'İsveç',
    ana_tur: 'votka',
    alt_tur: 'standart',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'tahıl'],
    alkol_seviye: 'sert',
    lore_short: 'İsveç kış sularının saflığı. 1879\\'dan beri aynı tarlaların buğdayından, aynı kaynağın suyundan üretilen "Tek Kaynak" (One Source) felsefesinin gururu.',
    lore_full: [
      { baslik: 'Köken', metin: 'Lars Olsson Smith tarafından 1879\\'da İsveç\\'in Åhus kasabasında "Absolut Rent Brännvin" (Kesinlikle Saf Votka) adıyla yaratıldı.' },
      { baslik: 'Yayılma', metin: 'Eczane şişelerinden ilham alan ikonik tasarımı ve zekice pazarlama kampanyalarıyla 80\\'ler Amerika\\'sını fethetti.' },
      { baslik: 'Kültürel Etki', metin: 'Votkayı sadece "kafayı bulmak" için içilen bir şey olmaktan çıkarıp, Andy Warhol gibi sanatçıların tuvaline taşıyan ilk markadır.' },
      { baslik: 'Modern Dönem', metin: 'Tüm buğdayı ve suyu hala tek bir kasabanın etrafından tedarik eder. Aromalı votka devriminin de öncülerindendir (Absolut Citron, Peppar vb.).' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'deki kulüp kültüründe Smirnoff ile birlikte en çok tüketilen, gece hayatının demirbaş votkasıdır.' }
    ],
    hammadde: 'Kış buğdayı ve Åhus derin kuyu suyu.',
    uretim_sureci: 'Sürekli damıtma (Continuous distillation).',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Şeffaf.',
    koku: 'Çok temiz, hafif tahıl ve taze ekmek kabuğu.',
    tat: 'Pürüzsüz, hafif tatlı (kış buğdayından), ağızda kremsi bir his.',
    finish: 'Temiz, hafif karabiber ısısı.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot', sicaklik: 'Buzluktan çıkmış', miktar: '40 ml', hazirlik: 'Sek içilebilir ama genelde mikserle tercih edilir.' },
    mix_detay: [],
    yiyecek: 'Somon, havyar, meze.',
    muzik_his: 'Pop, Elektronik.',
    mevsim: 'Her mevsim',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2', ideal: '4', limit_ustu: '6+', ertesi_gun: 1 },
    etki_hizi: 'Hızlı', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Absolut Elyx'], fiyat_araligi: '600 - 800', nereden_alinir: 'Tekeller', pop_kultur: 'Warhol\\'un şişesi.', yanlis_bilinenler: 'Rus votkası sanılır, İsveçlidir.', sozler: '"One Source."'
  },
  {
    id: 'grey-goose',
    name: 'Grey Goose',
    emoji: '🦢',
    color: '#002554',
    aliases: ['Gri Kaz'],
    origin: 'Fransa',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'çiçeksi'],
    alkol_seviye: 'sert',
    lore_short: 'Konyak bölgesinin votkaya dokunuşu. Fransız zarafetiyle üretilen, "Dünyanın en iyi lezzetli votkası" unvanını alarak ultra-premium kategorisini yaratan efsane.',
    lore_full: [
      { baslik: 'Köken', metin: '1997\\'de Amerikalı Sidney Frank tarafından yaratıldı. Üretimi için Konyak bölgesinin efsanevi Maître de Chai\\'si (Mahzen Ustası) François Thibault ikna edildi.' },
      { baslik: 'Yayılma', metin: 'Bir Konyak ustasının votka yapması Fransa\\'da tepki çekse de, ortaya çıkan ürün o kadar yumuşak ve zarifti ki Amerika\\'daki lüks barları bir gecede ele geçirdi.' },
      { baslik: 'Kültürel Etki', metin: 'Votkanın 10 dolarlık ucuz bir içkiden, 40 dolarlık bir statü sembolüne dönüşmesini sağlayan markadır.' },
      { baslik: 'Modern Dönem', metin: 'VIP masaların, lüks kulüplerin ve meşaleli şişelerin değişmez aktörüdür.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'deki lüks gece kulüplerinde "loca açtırma" ritüelinin en popüler premium şişesidir.' }
    ],
    hammadde: 'Picardie bölgesi kış buğdayı ve Gensac-la-Pallue kaynak suyu.',
    uretim_sureci: 'Konyak üretim tekniklerinden ilham alan 5 aşamalı özel damıtma.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Şeffaf.',
    koku: 'Taze çiçekler, çok hafif badem ve narenciye.',
    tat: 'İnanılmaz yumuşak. Adeta su gibi akıp giden ama arkada badem ve taze fırınlanmış hamur işi tatları bırakan bir profil.',
    finish: 'Çok uzun, hiç yakmayan, ılık bir bitiş.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Shot veya Martini Kadehi', sicaklik: 'Çok Soğuk', miktar: '40 ml', hazirlik: 'Buzlu veya sek.' },
    mix_detay: [],
    yiyecek: 'Havyar, istiridye, kaz ciğeri.',
    muzik_his: 'Deep House, Lüks Kulüp.',
    mevsim: 'Her mevsim',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2', ideal: '4', limit_ustu: '6+', ertesi_gun: 0 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Grey Goose'], fiyat_araligi: '1500 - 2000', nereden_alinir: 'Lüks tekel, makro.', pop_kultur: 'VIP masaların kralı.', yanlis_bilinenler: 'Tarihi bir marka sanılır, aslında çok yenidir (1997).', sozler: '"The World\\'s Best Tasting Vodka."'
  },
  {
    id: 'belvedere',
    name: 'Belvedere',
    emoji: '🧊',
    color: '#ffffff',
    aliases: ['Belvedere Vodka'],
    origin: 'Polonya',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'karabiber', 'vanilya'],
    alkol_seviye: 'sert',
    lore_short: 'Polonya\\'nın lüks cevheri. Tam 600 yıllık Polonya votka üretim kurallarına (sadece çavdar ve su) sadık kalınarak yaratılan karakterli ve güçlü bir premium.',
    lore_full: [
      { baslik: 'Köken', metin: 'İsmini Varşova\\'daki başkanlık sarayı Belweder\\'den alır. Şişesinin üzerinde sarayın çizimi bulunur.' },
      { baslik: 'Yayılma', metin: 'Grey Goose\\'un en büyük rakibidir. O Fransız buğday zarafetiyken, Belvedere Polonya çavdarının karakterini temsil eder.' },
      { baslik: 'Kültürel Etki', metin: '"Votkanın tadı olmaz" efsanesini yıkar. Çavdardan gelen o baharatlı ve vanilyalı tat profilini bariz şekilde hissedersiniz.' },
      { baslik: 'Modern Dönem', metin: 'LVMH (Louis Vuitton Moët Hennessy) grubunun elmaslarındandır. "Made with Nature" felsefesiyle hiçbir yapay katkı kullanmaz.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Gece kulüplerinde ve lüks barlarda "Grey Goose mu Belvedere mi?" tartışmasının sadık bir tarafıdır.' }
    ],
    hammadde: '%100 Polska Çavdarı (Dankowskie) ve kendi kuyu suları.',
    uretim_sureci: 'Dört kez damıtılır.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Şeffaf.',
    koku: 'Hafif vanilya, beyaz biber ve çavdar ekmeği.',
    tat: 'Grey Goose kadar "su gibi" değildir, damakta daha dolgun, hafif tatlı vanilya ve bariz karabiber/çavdar ısısı bırakır. Çok daha "karakterli" bir votkadır.',
    finish: 'Uzun, fındıksı ve baharatlı.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Shot veya Martini', sicaklik: 'Buzluktan (-18°C)', miktar: '40 ml', hazirlik: 'Sade veya Martini içinde.' },
    mix_detay: [],
    yiyecek: 'Ağır mezeler, et tartar, füme somon.',
    muzik_his: 'Tech House.',
    mevsim: 'Kış',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2', ideal: '4', limit_ustu: '6+', ertesi_gun: 1 },
    etki_hizi: 'Hızlı', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Belvedere'], fiyat_araligi: '1500 - 1800', nereden_alinir: 'Lüks market.', pop_kultur: 'James Bond Spectre filmindeki özel anlaşması.', yanlis_bilinenler: 'Sıradan bir votka gibi tatsız sanılır.', sozler: '"Beautiful to see, beautiful to taste."'
  },
  {
    id: 'stolichnaya',
    name: 'Stolichnaya',
    emoji: '⭐',
    color: '#cc0000',
    aliases: ['Stoli'],
    origin: 'Letonya / Rusya',
    ana_tur: 'votka',
    alt_tur: 'standart',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'tahıl'],
    alkol_seviye: 'sert',
    lore_short: 'Klasik Rus ekolü. Uzaya giden ilk votka, Batı bloğuna satılan ilk Sovyet votkası. Gerçek bir soğuk savaş efsanesi.',
    lore_full: [
      { baslik: 'Köken', metin: '1901 yılında Moskova\\'daki tarihi bir damıtımevinde doğdu. İsmi "Başkent" (Capital) anlamına gelir.' },
      { baslik: 'Yayılma', metin: 'Sovyetler Birliği döneminde devletin en prestijli ihraç ürünlerinden biriydi. Soğuk Savaş yıllarında Pepsi ile yapılan ünlü bir takas anlaşması sayesinde (Pepsi şurubu karşılığında Stoli) Amerika pazarına giren ilk Rus votkası oldu.' },
      { baslik: 'Kültürel Etki', metin: 'Uzay yarışında Apollo-Soyuz görevinde astronotlara/kozmonotlara tüp içinde Stoli ikram edilmiştir.' },
      { baslik: 'Modern Dönem', metin: 'Bugün uluslararası Stoli markası Letonya\\'da üretilir (Rusya içindeki devlet Stoli\\'si ile uluslararası Stoli ayrıdır). Aromalı votka konseptini (Stoli Ohranj, Stoli Razberi) 1960\\'larda başlatan ilk markadır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Özellikle eski kuşak barmenlerin ve gerçek "Rus stili" sert votka arayanların saygı duyduğu bir markadır.' }
    ],
    hammadde: 'Kış buğdayı, az miktarda çavdar ve artezyen suyu.',
    uretim_sureci: '3 kez damıtılır, kuvars kumu ve huş ağacı kömüründen filtrelenir.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Şeffaf.',
    koku: 'Alkol önde, marshmallow ve mineral notaları.',
    tat: 'Tatlı bir giriş, ardından meyvemsi (narenciye kabuğu) ve sıcak, mineral ağırlıklı sert bir gövde.',
    finish: 'Temiz, sıcak, hafif baharatlı.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot', sicaklik: 'Çok soğuk', miktar: '40 ml', hazirlik: 'Tek dikişte.' },
    mix_detay: [],
    yiyecek: 'Turşu, Rus salatası, siyah ekmek.',
    muzik_his: 'Sovyet marşları, Retro Synth.',
    mevsim: 'Kış',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2', ideal: '4', limit_ustu: '6+', ertesi_gun: 1 },
    etki_hizi: 'Çok hızlı', metabolizma: 'Orta', baslangic_onerileri: ['-'], orta_seviye: ['Stoli'], premium: ['Stoli Elit'], fiyat_araligi: '500 - 700', nereden_alinir: 'Market, tekel.', pop_kultur: 'Uzaya çıkan içki.', yanlis_bilinenler: 'Hala Rusya\\'da üretildiği sanılır (Küresel pazar için Letonya\\'da üretilir).', sozler: '"The Mother of all Vodkas."'
  },
  {
    id: 'ketel-one',
    name: 'Ketel One',
    emoji: '⚗️',
    color: '#b3b3b3',
    aliases: ['Ketel'],
    origin: 'Hollanda',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'taze', 'limon'],
    alkol_seviye: 'sert',
    lore_short: 'Barmenlerin favorisi. Nolet ailesi tarafından Hollanda\\'da 300 yıllık bir ustalıkla, bakır imbiklerde (Pot Still) üretilen karakterli bir Hollanda votkası.',
    lore_full: [
      { baslik: 'Köken', metin: 'Hollanda\\'nın Schiedam kentinde, Nolet ailesi tarafından yaratıldı. İsim, üretildiği orijinal kömür ateşli bakır imbiğin adı olan "Distilleerketel #1"den gelir.' },
      { baslik: 'Yayılma', metin: 'Pazarlamaya devasa bütçeler ayırmak yerine, Amerika\\'daki barmenlere tek tek şişe gönderip tattırarak (grassroots marketing) zirveye oturdular.' },
      { baslik: 'Kültürel Etki', metin: 'Dünyanın en iyi barlarında (World\\'s 50 Best Bars) yapılan anketlerde yıllardır "Barmenlerin En Çok Tercih Ettiği" (Top Trending) votka seçilir.' },
      { baslik: 'Modern Dönem', metin: 'Sürekli damıtma ile "Pot Still" (geleneksel bakır imbik) damıtmasını harmanlayarak, hem çok temiz hem de inanılmaz karakterli bir sıvı elde ederler.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Üst düzey kokteyl barlarında, barmenlerin favori kokteyl votkasıdır.' }
    ],
    hammadde: '%100 Avrupa kış buğdayı.',
    uretim_sureci: 'Sürekli damıtma + Bakır İmbik (Pot Still) harmanı. Kömür ateşinde damıtılır.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Şeffaf.',
    koku: 'Taze, narenciye, rezene ve anason esintileri.',
    tat: 'İnanılmaz pürüzsüz ama "boş" değil. Karakterli, ağız kaplayan (viskoz), taze limon, bal ve hafif karabiber.',
    finish: 'Uzun, canlı ve ferahlatıcı.',
    vucut: 'Medium to Full',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot veya Martini', sicaklik: 'Soğuk', miktar: '40 ml', hazirlik: 'Sade veya buzlu.' },
    mix_detay: [],
    yiyecek: 'Peynir tabağı, karides kokteyl.',
    muzik_his: 'Jazz, Soul.',
    mevsim: 'İlkbahar, Yaz',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2', ideal: '4', limit_ustu: '6+', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['Ketel One'], premium: ['-'], fiyat_araligi: '900 - 1300', nereden_alinir: 'İyi tekeller.', pop_kultur: 'Barmenlerin gizli silahı.', yanlis_bilinenler: 'Rus votkası sanılır, Hollandalıdır.', sozler: '"Barmenlerin tercihi."'
  }`;

let content = fs.readFileSync('src/data/votka.js', 'utf-8');
content = content.replace(/\\n\\];/, ",\\n" + extraVotka + "\\n];");
fs.writeFileSync('src/data/votka.js', content);
console.log('5 Votka eklendi.');
