const fs = require('fs');

const extraBira = `  {
    id: 'gara-guzu',
    name: 'Gara Guzu',
    emoji: '🍺',
    color: '#d48806',
    aliases: ['Muğla Birası'],
    origin: 'Türkiye',
    ana_tur: 'bira',
    alt_tur: 'craft',
    gorunum: 'bulanık',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['şerbetçiotu', 'meyvemsi'],
    alkol_seviye: 'orta',
    lore_short: 'Türkiye craft bira devriminin öncüsü. Muğla\\'da kurulan küçük bir aile işletmesinin, butik birayı Türk insanıyla tanıştırma hikayesi.',
    lore_full: [
      { baslik: 'Köken', metin: '2014 yılında Muğla\\'da kurulan Türkiye\\'nin ilk mikrobira fabrikalarından (microbrewery) biridir. İsim, Muğla ağzıyla "kara kuzu" (farklı olan, siyah koyun) anlamına gelir.' },
      { baslik: 'Yayılma', metin: 'İlk başlarda sadece İstanbul\\'daki bazı seçkin craft bira barlarında bulunurken, günümüzde zincir marketlere girmeyi başarmıştır.' },
      { baslik: 'Kültürel Etki', metin: 'Sarı ve şeffaf endüstriyel biralardan başka bira bilmeyen kitleye "Blonde Ale", "Amber Ale", "IPA" gibi türleri öğretmiştir.' },
      { baslik: 'Modern Dönem', metin: 'Tasarım etiketleri ve yerel içerik kullanımıyla (örneğin pancarlı bira) craft ruhunu korumaya devam eder.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türk craft bira kültürünün başlangıç noktası sayılır.' }
    ],
    hammadde: 'Muğla suyu, İngiliz/Alman maltları, çeşitli şerbetçiotları.',
    uretim_sureci: 'Ale tipi üst fermantasyon, pastörize ve filtre edilmemiş.',
    dinlendirme: 'Kısa süre dinlendirme.',
    renk: 'Bulanık altın sarısı veya amber.',
    koku: 'Meyvemsi esterler, şerbetçiotu ve malt karakteri.',
    tat: 'Endüstriyel biralara göre çok daha gövdeli, malt tatlılığı ile şerbetçiotu acılığının dengesi.',
    finish: 'Orta uzunlukta, hafif acımsı.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Lale veya Teku Kadehi', sicaklik: 'Soğuk (6-8°C)', miktar: '330 ml', hazirlik: 'Şişenin dibindeki maya tortusu isteğe göre çalkalanıp bardağa eklenebilir.' },
    mix_detay: [],
    yiyecek: 'Ev yapımı burgerler, sosisli, patates kızartması.',
    muzik_his: 'Indie Rock, Alternatif.',
    mevsim: 'Her mevsim',
    abv_range: '4.5 - 6',
    standart_porsiyon: '330',
    kafa_dozu: { hafif: '1-2 şişe', ideal: '3 şişe', limit_ustu: '5+ şişe', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['Gara Guzu Blonde Ale'], orta_seviye: ['Gara Guzu Amber Ale'], premium: ['Gara Guzu Mayhoş'], fiyat_araligi: '100 - 150', nereden_alinir: 'Marketler, craft barlar.', pop_kultur: 'Craft biraya girişin ilk adresidir.', yanlis_bilinenler: 'İçinde kuzu eti olduğu gibi absürt esprilere maruz kalır.', sozler: '"Sürünün kara kuzusu."'
  },
  {
    id: 'feliz',
    name: 'Feliz Kulpa',
    emoji: '🍻',
    color: '#ffc107',
    aliases: ['Feliz'],
    origin: 'Türkiye',
    ana_tur: 'bira',
    alt_tur: 'craft',
    gorunum: 'bulanık',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['tropik', 'şerbetçiotu'],
    alkol_seviye: 'orta',
    lore_short: 'İstanbul\\'un craft bira temsilcilerinden. Özellikle Smash (Single Malt and Single Hop) türü biralarıyla şerbetçiotu profilini öne çıkaran butik marka.',
    lore_full: [
      { baslik: 'Köken', metin: 'İstanbul\\'da butik olarak üretilmeye başlanan, modern ve eğlenceli bir marka kimliğine sahip craft bira üreticisi.' },
      { baslik: 'Yayılma', metin: 'Moda, Kadıköy ve Karaköy gibi craft bira kültürünün yoğun olduğu yerlerdeki musluklardan (tap) bardaklara doldu.' },
      { baslik: 'Kültürel Etki', metin: 'Craft biranın sadece ciddi bir "tadım" olayı değil, aynı zamanda eğlenceli ve rahat bir kültür olduğunu gösterdi.' },
      { baslik: 'Modern Dönem', metin: 'Renkli kutu tasarımları ve farklı şerbetçiotu denemeleriyle gençler arasında çok popüler.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'deki yeni nesil pub kültürünün demirbaşlarındandır.' }
    ],
    hammadde: 'Malt, tek çeşit şerbetçiotu (SMASH için), maya.',
    uretim_sureci: 'Ale fermantasyonu, dry-hopping (soğuk şerbetçiotu ekleme).',
    dinlendirme: 'Kısa süre.',
    renk: 'Bulanık sarı.',
    koku: 'Yoğun tropik meyveler (mango, ananas), narenciye ve çam.',
    tat: 'Meyvemsi ferahlık ve ardından gelen belirgin, temiz bir şerbetçiotu acılığı.',
    finish: 'Uzun, tazeleyici ve şerbetçiotu karakterli.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'IPA Kadehi veya Nonic Pint', sicaklik: 'Soğuk (6-8°C)', miktar: '330 ml', hazirlik: 'Kutudan hızlıca bardağa.' },
    mix_detay: [],
    yiyecek: 'Baharatlı taco, tavuk kanadı, nachos.',
    muzik_his: 'Pop-Punk, Indie Pop.',
    mevsim: 'Yaz, İlkbahar',
    abv_range: '5',
    standart_porsiyon: '330',
    kafa_dozu: { hafif: '1-2 kutu', ideal: '3-4 kutu', limit_ustu: '5+ kutu', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['Feliz Smash IPA'], orta_seviye: ['-'], premium: ['-'], fiyat_araligi: '110 - 160', nereden_alinir: 'Tekeller, craft publar.', pop_kultur: 'Kutu tasarımıyla Instagram fotoğraflarında sıkça yer alır.', yanlis_bilinenler: 'Bulanık olması bozuk olduğu anlamına gelmez, filtrelenmemiştir.', sozler: '"Şerbetçiotunun mutluluğu."'
  },
  {
    id: 'yeni-dunya',
    name: 'Yeni Dünya',
    emoji: '🍺',
    color: '#8c5922',
    aliases: ['YD'],
    origin: 'Türkiye',
    ana_tur: 'bira',
    alt_tur: 'craft',
    gorunum: 'koyu',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['kavrulmuş', 'karamel'],
    alkol_seviye: 'orta',
    lore_short: 'Craft biracılığa farklı bir soluk. Yerel malzemelere (örneğin keçiboynuzu) ağırlık veren, yenilikçi ve deneysel üretim tarzı.',
    lore_full: [
      { baslik: 'Köken', metin: 'Anadolu\\'nun malzemeleriyle dünya bira stillerini birleştirme vizyonuyla kurulan butik bira markası.' },
      { baslik: 'Yayılma', metin: 'Özellikle tadım atölyelerinde ve craft bira festivallerinde dikkat çekti.' },
      { baslik: 'Kültürel Etki', metin: 'Biraya sadece malt ve şerbetçiotu gözüyle bakmayan, "yerel eklentiler" (adjunct) trendini getiren üreticilerdendir.' },
      { baslik: 'Modern Dönem', metin: 'Sınırlı üretim serileriyle meraklı kitleyi sürekli heyecanlandırır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Gastronomik restoranlarda yemek eşleşmelerinde sıkça kullanılır.' }
    ],
    hammadde: 'Malt, maya, yöresel eklentiler (meyve, baharat).',
    uretim_sureci: 'Deneysel ale fermantasyonları.',
    dinlendirme: 'Partiye göre değişir.',
    renk: 'Amberden koyu kahveye kadar değişir.',
    koku: 'Karamel, bisküvi, kavrulmuş notalar ve eklentinin (meyve/baharat) karakteri.',
    tat: 'Kompleks, standart dışı, bazen mayhoş, bazen tatlımsı baharatlı.',
    finish: 'Uzun ve akılda kalıcı.',
    vucut: 'Medium to Full',
    rakon: 'sek',
    sek_detay: { kadeh: 'Tadım Kadehi (Snifter)', sicaklik: 'Serin (8-12°C)', miktar: '330 ml', hazirlik: 'Çok soğuk içilmemelidir.' },
    mix_detay: [],
    yiyecek: 'Tütsülenmiş etler, eski peynirler, karamelli tatlılar.',
    muzik_his: 'Anadolu Rock, Etnik Caz.',
    mevsim: 'Sonbahar ve Kış',
    abv_range: '5 - 7',
    standart_porsiyon: '330',
    kafa_dozu: { hafif: '1 şişe', ideal: '2-3 şişe', limit_ustu: '4+ şişe', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['Yeni Dünya Amber'], orta_seviye: ['Yeni Dünya Porter'], premium: ['-'], fiyat_araligi: '120 - 180', nereden_alinir: 'Özel craft dükkanları.', pop_kultur: 'Bira gurmelerinin radarındadır.', yanlis_bilinenler: 'Meyveli biraların şekerli olduğu sanılır, Yeni Dünya genelde sektir.', sozler: '"Kadehte yeni bir kıta."'
  },
  {
    id: 'guinness',
    name: 'Guinness',
    emoji: '🍺',
    color: '#1a1005',
    aliases: ['Siyah Bira', 'Stout'],
    origin: 'İrlanda',
    ana_tur: 'bira',
    alt_tur: 'ithal',
    gorunum: 'opak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['kavrulmuş', 'kahve', 'kremsi'],
    alkol_seviye: 'hafif',
    lore_short: 'İrlanda\\'nın sıvı ekmeği. Dünyanın en ünlü Stout birası. Siyah rengi, kremşanti gibi kalıcı köpüğü ve kavrulmuş arpa karakteriyle efsanevi bir ikon.',
    lore_full: [
      { baslik: 'Köken', metin: '1759\\'da Arthur Guinness\\'in Dublin\\'deki St. James\\'s Gate fabrikasını yıllık 45 pound\\'a 9000 yıllığına kiralamasıyla başlayan efsane.' },
      { baslik: 'Yayılma', metin: 'İrlanda diasporası ve İngiliz İmparatorluğu ile tüm dünyaya yayıldı. Günümüzde dünyanın her yerinde bir İrlanda Pub\\'ı bulabilirsiniz.' },
      { baslik: 'Kültürel Etki', metin: 'Stout (siyah bira) kategorisini tek başına domine eden, "Siyah bira içmem" diyenlerin bile sevdiği benzersiz yapı.' },
      { baslik: 'Modern Dönem', metin: 'Kutu versiyonlarındaki o meşhur köpüğü yaratmak için kutunun içine "widget" (küçük bir azot topu) yerleştiren mühendislik harikasıdır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'deki İrlanda publarının belkemiğidir. 17 Mart St. Patrick Günü kutlamalarında su gibi akar.' }
    ],
    hammadde: 'Kavrulmuş arpa, malt arpa, şerbetçiotu, İrlanda suyu ve meşhur Guinness mayası.',
    uretim_sureci: 'Üst fermantasyon. Draught (fıçı/kutu) versiyonu nitrojen (azot) gazı ile basılır, bu ona o eşsiz kremsi köpüğü verir.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Kapkara görünür ama ışığa tutulduğunda aslında çok koyu bir yakut kırmızısıdır.',
    koku: 'Kavrulmuş kahve, bitter çikolata ve hafif malt.',
    tat: 'Kremamsı bir pürüzsüzlük, kavruk arpa acılığı ve hafif tatlımsı bir gövde. Rengine rağmen oldukça hafif içimlidir.',
    finish: 'Kuru, kavrulmuş ve çok tatminkar.',
    vucut: 'Medium to Full (Ama hafif hissettirir)',
    rakon: 'sek',
    sek_detay: { kadeh: 'Guinness Tulip Kadehi (Pint)', sicaklik: 'Soğuk (6°C)', miktar: '500 ml', hazirlik: 'İki aşamalı döküm: Kadeh 45 derece eğilir, ¾\\'ü doldurulur, köpüğün çökmesi için beklenir, sonra dik olarak üstü tamamlanır.' },
    mix_detay: [ { isim: 'Irish Car Bomb', malzemeler: ['½ Pint Guinness', '½ Shot Baileys', '½ Shot Jameson'], hazirlanis: 'Shot bardağı biranın içine bırakılır ve tek dikişte içilir.', neden: 'Pub eğlencesi.', ortam: 'Gece yarısı.' } ],
    yiyecek: 'İstiridye (klasik eşleşme), etli pay, ızgara sosis.',
    muzik_his: 'İrlanda Folk Müziği, Kelt Ezgileri.',
    mevsim: 'Sonbahar ve Kış',
    abv_range: '4.2',
    standart_porsiyon: '500',
    kafa_dozu: { hafif: '1-2 pint', ideal: '3-4 pint', limit_ustu: '6+ pint', ertesi_gun: 1 },
    etki_hizi: 'Yavaş (Alkolü düşüktür)', metabolizma: 'Hızlı', baslangic_onerileri: ['Guinness Draught'], orta_seviye: ['-'], premium: ['Guinness Extra Stout'], fiyat_araligi: '150 - 250', nereden_alinir: 'Publar ve makro marketler.', pop_kultur: 'Guinness Rekorlar Kitabı aslında bu bira markasının publardaki tartışmaları çözmek için bastırdığı bir kitaptır.', yanlis_bilinenler: 'Rengi koyu olduğu için çok sert, ağır veya yüksek alkollü sanılır; aksine çok hafif ve düşük alkollüdür (sadece 4.2%).', sozler: '"Good things come to those who wait."'
  },
  {
    id: 'weihenstephaner',
    name: 'Weihenstephaner',
    emoji: '🍺',
    color: '#ffdf80',
    aliases: ['Alman Buğday', 'Hefeweizen'],
    origin: 'Almanya',
    ana_tur: 'bira',
    alt_tur: 'ithal',
    gorunum: 'bulanık',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['muz', 'karanfil', 'buğday'],
    alkol_seviye: 'orta',
    lore_short: 'Dünyanın faaliyet gösteren en eski bira fabrikası (M.S. 1040). Bavyera buğday birasının (Hefeweizen) dünyadaki referans standardıdır.',
    lore_full: [
      { baslik: 'Köken', metin: 'Almanya\\'nın Bavyera bölgesinde, Weihenstephan manastırında keşişler tarafından MS 1040 yılında kurulmuştur. 1000 yıla yakın bir süredir kesintisiz bira üretmektedir.' },
      { baslik: 'Yayılma', metin: 'Dünya çapında buğday birası denince akla gelen ilk, en saygın ve en çok ödül alan markadır.' },
      { baslik: 'Kültürel Etki', metin: 'Biranın sadece acı bir içecek olmadığını, muz ve karanfil gibi şaşırtıcı tatlara sahip olabileceğini insanlara kanıtlar.' },
      { baslik: 'Modern Dönem', metin: 'Münih Teknik Üniversitesi kampüsünde bulunur, aynı zamanda dünyanın en iyi bira üretim okuludur.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'deki premium pubların musluklarında (tap) en çok aranan ithal biralardan biridir. Buğday birası sevgisini Türkiye\\'ye aşılamıştır.' }
    ],
    hammadde: '%50\\'den fazla buğday maltı, arpa maltı, Bavyera şerbetçiotu ve özel manastır mayası.',
    uretim_sureci: 'Ale tipi üst fermantasyon, filtre edilmez (Hefe: Maya, Weizen: Buğday).',
    dinlendirme: 'Kısa süre.',
    renk: 'Bulanık sarı-turuncu. Kar beyaz, çok yoğun ve kalın bir köpüğü vardır.',
    koku: 'İnanılmaz karakteristik: Olgun muz, karanfil baharatı, sakız ve buğday ekmeği.',
    tat: 'Tatlımsı, meyvemsi, asiditesi canlı. Şerbetçiotu acılığı neredeyse hiç hissedilmez. Çok doyurucu bir gövde.',
    finish: 'Meyvemsi, hafif karanfil baharatı ile sonlanan yumuşak bitiş.',
    vucut: 'Medium to Full (Kremamsı)',
    rakon: 'sek',
    sek_detay: { kadeh: 'Uzun Buğday Birası Kadehi (Weizenvase)', sicaklik: 'Soğuk (6-8°C)', miktar: '500 ml', hazirlik: 'Bardağın %80\\'i eğik doldurulur. Şişenin dibinde kalan bir miktar bira çalkalanarak mayanın karışması sağlanır ve bardağın en üstüne köpüklü bir taç olarak eklenir.' },
    mix_detay: [],
    yiyecek: 'Beyaz sosis (Weißwurst), pretzel, tavuk şinitzel, meyveli tatlılar.',
    muzik_his: 'Klasik Alman Halk Müziği.',
    mevsim: 'Yaz ve İlkbahar',
    abv_range: '5.4',
    standart_porsiyon: '500',
    kafa_dozu: { hafif: '1-2 bardak', ideal: '3 bardak', limit_ustu: '4+ bardak (Mideyi çok doldurur)', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['Weihenstephaner Hefe Weissbier'], orta_seviye: ['Weihenstephaner Dunkel (Koyu)'], premium: ['Weihenstephaner Vitus'], fiyat_araligi: '150 - 220', nereden_alinir: 'İyi publar ve büyük marketler.', pop_kultur: 'Bira gurmelerinin buğday birası dendiğinde "The Benchmark" (referans noktası) kabul ettiği biradır.', yanlis_bilinenler: 'İçinde muz veya karanfil olduğu sanılır, hayır; bu tatları sadece o eşsiz "maya" (yeast) fermantasyon sırasında üretir.', sozler: '"Bin yıllık ustalık."'
  },
  {
    id: 'pilsner-urquell',
    name: 'Pilsner Urquell',
    emoji: '🍺',
    color: '#ffd700',
    aliases: ['İlk Pilsner', 'Urquell'],
    origin: 'Çek Cumhuriyeti',
    ana_tur: 'bira',
    alt_tur: 'ithal',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['şerbetçiotu', 'malt'],
    alkol_seviye: 'orta',
    lore_short: 'Dünyadaki ilk altın sarısı, berrak bira (1842). Bugün dünyada tüketilen biraların %90\\'ından fazlası (Pilsner stili) bu biranın taklididir. Orijinal kaynak budur.',
    lore_full: [
      { baslik: 'Köken', metin: '1842\\'de Çekya\\'nın Plzeň (Pilsen) şehrinde Bavyeralı bira ustası Josef Groll tarafından icat edildi. "Urquell" Almanca "orijinal kaynak" demektir.' },
      { baslik: 'Yayılma', metin: 'Cam bardakların yaygınlaştığı bir döneme denk geldiği için, berrak ve altın sarısı rengi büyük sükse yaptı ve tüm dünyayı ele geçirdi.' },
      { baslik: 'Kültürel Etki', metin: 'Pilsner (Pils) adındaki bütün bir bira kategorisinin atasıdır. Efes Pilsen, Carlsberg, Heineken dahil hepsi onun torunudur.' },
      { baslik: 'Modern Dönem', metin: 'Hala orijinal tarifle, özel Saaz şerbetçiotu ve yumuşak Pilsen suyuyla üretilir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Gerçek bir Pilsner\\'in o harika acılığını tatmak isteyen bira severlerin özel tercihidir.' }
    ],
    hammadde: 'Moravia maltı, Bohemia Saaz (Žatec) şerbetçiotu, Pilsen\\'in aşırı yumuşak suyu.',
    uretim_sureci: 'Lager (alt fermantasyon) tipi, uzun süre soğukta olgunlaştırma.',
    dinlendirme: 'Soğuk mahzende dinlendirilmiş.',
    renk: 'Parlak altın sarısı.',
    koku: 'Saaz şerbetçiotunun çiçeksi ve baharatlı kokusu, hafif tereyağlı (diasetil) malt karakteri.',
    tat: 'Önce tatlımsı ekmek/malt, hemen ardından gelen çok net, asil ve tazeleyici bir şerbetçiotu acılığı. (Normal biralardan daha acıdır).',
    finish: 'Uzun, temiz ve belirgin şekilde acı.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Pilsner Kadehi (Uzun ve ince)', sicaklik: 'Soğuk (4-7°C)', miktar: '500 ml', hazirlik: 'Köpük kalın bırakılmalı, köpüğü biranın oksitlenmesini engeller.' },
    mix_detay: [],
    yiyecek: 'Gulaş, kızarmış domuz, baharatlı sosis, patates.',
    muzik_his: 'Klasik Müzik.',
    mevsim: 'Her mevsim',
    abv_range: '4.4',
    standart_porsiyon: '500',
    kafa_dozu: { hafif: '1-2 şişe', ideal: '3-4 şişe', limit_ustu: '5+ şişe', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['Pilsner Urquell'], premium: ['-'], fiyat_araligi: '130 - 180', nereden_alinir: 'Büyük marketler.', pop_kultur: 'Bira tarihini değiştiren sıvı altın.', yanlis_bilinenler: 'Sıradan bir lager sanılır, tadımcılar için dünyanın en önemli biralarından biridir.', sozler: '"Her şeyin başladığı yer."'
  },
  {
    id: 'chimay',
    name: 'Chimay',
    emoji: '🍺',
    color: '#a52a2a',
    aliases: ['Trappist', 'Keşiş Birası'],
    origin: 'Belçika',
    ana_tur: 'bira',
    alt_tur: 'ithal',
    gorunum: 'bulanık',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['meyvemsi', 'kuru üzüm', 'baharatlı'],
    alkol_seviye: 'sert',
    lore_short: 'Gerçek keşişlerin, bir manastırın duvarları ardında ürettiği otantik "Trappist" birası. Yüksek alkollü, inanılmaz kompleks ve yıllandıkça güzelleşen bir şaheser.',
    lore_full: [
      { baslik: 'Köken', metin: 'Belçika\\'daki Scourmont Manastırı\\'nda, Trappist tarikatı keşişleri tarafından üretilir. "Authentic Trappist Product" logosu taşır (Dünyada sadece birkaç manastır bu logoyu taşıyabilir).' },
      { baslik: 'Yayılma', metin: 'Dünyadaki en prestijli, tarihi ve saygı gören Belçika biralarındandır.' },
      { baslik: 'Kültürel Etki', metin: 'Bira kültürünün ne kadar derin ve "şarapvari" olabileceğini gösterir. Gelirlerin çoğu hayır işlerine bağışlanır.' },
      { baslik: 'Modern Dönem', metin: 'Kırmızı (Rouge/Première), Beyaz (Cinq Cents) ve Mavi (Bleue/Grande Réserve) renk kodlarıyla bilinir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Özel bira butiklerinde ve lüks otel barlarında gurmeler için bekler.' }
    ],
    hammadde: 'Malt, maya (özel keşiş mayası), su.',
    uretim_sureci: 'Ale tipi. Şişede canlı maya ile ikinci fermantasyon.',
    dinlendirme: 'Şişede yıllanabilir (Özellikle Mavi etiket yıllandıkça şaraplaşır).',
    renk: 'Kırmızı etiket: Bakır, Mavi etiket: Koyu kahve.',
    koku: 'Kuru meyveler (incir, kuru üzüm), karamel, fırınlanmış ekmek ve Belçika mayasının esterleri.',
    tat: 'Müthiş zengin. Malt tatlılığı, siyah meyve kompostosu ve alkolün ısıtıcı etkisi. Şerbetçiotu acılığı düşüktür.',
    finish: 'Uzun, ısıtıcı, şarapsı ve tatlımsı.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Trappist Kadehi (Geniş kadeh / Chalice)', sicaklik: 'Mahzen sıcaklığı (10-12°C)', miktar: '330 ml', hazirlik: 'Çok soğuk içilmez, şarap gibi oda sıcaklığına yakın içilmeli.' },
    mix_detay: [],
    yiyecek: 'Chimay Peyniri (kendi manastır peynirleri), ağır et yahnileri, bitter çikolata.',
    muzik_his: 'Kilise Korosu, Gregorian Chants, Klasik.',
    mevsim: 'Kış',
    abv_range: '7 - 9',
    standart_porsiyon: '330',
    kafa_dozu: { hafif: '1 şişe', ideal: '2 şişe', limit_ustu: '3+ şişe', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['Chimay Rouge (Kırmızı) %7'], orta_seviye: ['Chimay Blanche (Beyaz) %8'], premium: ['Chimay Bleue (Mavi) %9'], fiyat_araligi: '250 - 350', nereden_alinir: 'Premium butikler.', pop_kultur: 'Saygı duyulan manastır mirası.', yanlis_bilinenler: 'Bira olduğu için "dikilir" sanılır, yudum yudum şarap gibi içilir.', sozler: '"Keşişlerin duası."'
  }`;

let content = fs.readFileSync('src/data/bira.js', 'utf-8');
content = content.replace(/\n\];/, `,\n${extraBira}\n];`);
fs.writeFileSync('src/data/bira.js', content);
console.log("7 Bira added.");
