const fs = require('fs');

const extraViski = `  {
    id: 'talisker-10',
    name: 'Talisker 10',
    emoji: '🥃',
    color: '#d4af37',
    aliases: ['Talisker'],
    origin: 'İskoçya (Isle of Skye)',
    ana_tur: 'viski',
    alt_tur: 'single_malt',
    gorunum: 'berrak',
    olgunlasma: 'fıçılanmış',
    aroma: ['isli', 'deniz tuzu', 'karabiber'],
    alkol_seviye: 'sert',
    lore_short: 'Fırtınalı denizlerin viskisi. Isle of Skye adasının tek damıtımevinden çıkan, deniz tuzu, hafif turba isi ve bitişindeki o meşhur karabiber patlamasıyla karakterize olmuş güçlü bir malt.',
    lore_full: [
      { baslik: 'Köken', metin: '1830\\'da İskoçya\\'nın Skye adasında kurulan damıtımevi, adanın sert iklimini ve deniz rüzgarlarını fıçılarına hapseder. Etiketindeki "Made by the Sea" (Deniz tarafından yapıldı) sloganı boşuna değildir.' },
      { baslik: 'Yayılma', metin: 'Diageo\\'nun klasik maltlar serisinin bir parçası olmasıyla dünya çapında "ada maltları" kategorisinin referansı olmuştur.' },
      { baslik: 'Kültürel Etki', metin: 'İsli viskilere giriş yapmak isteyen ama Laphroaig kadar tıbbi bir koku istemeyenlerin en güvendiği basamaktır. Turba isi vardır ama deniz notalarıyla dengelenir.' },
      { baslik: 'Modern Dönem', metin: 'Tadım yarışmalarında 10 yıllık viskiler arasında en çok altın madalya kazanan efsanelerden biridir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Viski kültürü gelişen Türk tüketicisinin "biraz daha kompleks bir şeyler denemeliyim" dediğinde ilk aldığı şişelerdendir.' }
    ],
    hammadde: 'Orta seviye turbalanmış malt arpa, Skye adasının suları.',
    uretim_sureci: 'Çift damıtma, U şeklindeki özel imbik boruları.',
    dinlendirme: '10 yıl Amerikan meşesi (eski bourbon) fıçılar.',
    renk: 'Parlak altın.',
    koku: 'Deniz iyotu, istiridye kabuğu, hafif kamp ateşi isi ve narenciye kabuğu.',
    tat: 'Zengin kurutulmuş meyve tatlılığı, ardından gelen yoğun arpa, duman ve deniz tuzu.',
    finish: 'Çok uzun, ısıtıcı ve damağın arkasında beliren çok net "beyaz karabiber" acılığı.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Glencairn veya Snifter', sicaklik: 'Oda sıcaklığı', miktar: '40 ml', hazirlik: 'Asla buz atılmaz. Belki sadece 1-2 damla su.' },
    mix_detay: [],
    yiyecek: 'Tütsülenmiş somon, istiridye, eski kaşar, yoğun çikolata.',
    muzik_his: 'Kelt Müziği, Post-Rock.',
    mevsim: 'Kış',
    abv_range: '45.8',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 kadeh', ideal: '2 kadeh', limit_ustu: '3+ kadeh', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['-'], orta_seviye: ['Talisker 10'], premium: ['Talisker 18', 'Talisker Port Ruighe'], fiyat_araligi: '1400 - 1800', nereden_alinir: 'Tekeller, büyük marketler.', pop_kultur: 'Denizci viskisi olarak bilinir.', yanlis_bilinenler: 'Islay viskisi (Laphroaig vb) sanılır, hayır Islay\\'dan değil Skye adasındandır.', sozler: '"Made by the sea."'
  },
  {
    id: 'yamazaki-12',
    name: 'Yamazaki 12',
    emoji: '🥃',
    color: '#cca300',
    aliases: ['Suntory Yamazaki'],
    origin: 'Japonya',
    ana_tur: 'viski',
    alt_tur: 'japon',
    gorunum: 'berrak',
    olgunlasma: 'fıçılanmış',
    aroma: ['çiçeksi', 'baharatlı', 'mizunara meşesi'],
    alkol_seviye: 'sert',
    lore_short: 'Japon viski sanatının zirvesi. Şeftali, bal ve Japon Mizunara meşesinden gelen eşsiz tütsü kokularıyla, kusursuz dengeyi arayanların viskisi.',
    lore_full: [
      { baslik: 'Köken', metin: '1923\\'te Shinjiro Torii tarafından Kyoto yakınlarındaki Yamazaki vadisinde kurulan Japonya\\'nın ilk ticari viski damıtımevinden çıkar.' },
      { baslik: 'Yayılma', metin: '2010\\'larda Japon viskilerinin İskoçları geçerek dünyanın en iyi viskileri seçilmesiyle kara borsaya düşecek kadar popülerleşti.' },
      { baslik: 'Kültürel Etki', metin: 'İskoç geleneğini alıp, Japon zanaatkarlığı (shokunin) ve doğaya saygı felsefesiyle mükemmelleştirme hikayesidir.' },
      { baslik: 'Modern Dönem', metin: 'Bugün bulması çok zordur ve fiyatı karaborsada inanılmaz yükselmiştir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Lüks restoran ve otel barlarında "prestige" kadeh olarak sunulur.' }
    ],
    hammadde: 'İthal ve yerli malt, Yamazaki vadisinin ultra saf suyu.',
    uretim_sureci: 'Çeşitli boy ve şekillerdeki imbiklerde damıtılıp blend edilir.',
    dinlendirme: '12 yıl; Amerikan, İspanyol ve en önemlisi Japon Mizunara meşe fıçılarında.',
    renk: 'Saf altın.',
    koku: 'Şeftali, ananas, greyfurt, karanfil, Japon tütsüsü (Mizunara etkisi).',
    tat: 'İnanılmaz yumuşak. Hindistan cevizi, kızılcık ve tereyağlı bal.',
    finish: 'Uzun, tatlı zencefil ve hafif ahşap.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Glencairn', sicaklik: 'Oda sıcaklığı', miktar: '40 ml', hazirlik: 'Sade (Sek).' },
    mix_detay: [ { isim: 'Japon Highball', malzemeler: ['1 ölçü Yamazaki', '3 ölçü çok gazlı soda'], hazirlanis: 'Uzun bardakta, kristal buzla. Ancak genelde daha ucuz viskilerle (Toki) yapılır.', neden: 'Japonlar yemekle içmek için viskiyi sodayla açarlar.', ortam: 'Japon restoranı.' } ],
    yiyecek: 'Sushi, Sashimi, hafif tempura.',
    muzik_his: 'Jazz, Minimalist.',
    mevsim: 'İlkbahar',
    abv_range: '43',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 kadeh', ideal: '2 kadeh', limit_ustu: '3+ kadeh (Çok pahalıdır)', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['-'], orta_seviye: ['Suntory Toki'], premium: ['Yamazaki 12', 'Yamazaki 18'], fiyat_araligi: '8000 - 15000', nereden_alinir: 'Özel ithalat, lüks tekel.', pop_kultur: 'Bill Murray\\'nin "Lost in Translation" filmindeki "For relaxing times, make it Suntory time" repliğinin kahramanıdır.', yanlis_bilinenler: 'Pirinçten yapıldığı sanılır, %100 malt arpadan yapılır.', sozler: '"Suntory zamanı."'
  },
  {
    id: 'redbreast-12',
    name: 'Redbreast 12',
    emoji: '🥃',
    color: '#b35900',
    aliases: ['İrlanda Kuşu', 'Redbreast'],
    origin: 'İrlanda (Midleton)',
    ana_tur: 'viski',
    alt_tur: 'irish',
    gorunum: 'berrak',
    olgunlasma: 'fıçılanmış',
    aroma: ['meyvemsi', 'baharatlı', 'kremamsı'],
    alkol_seviye: 'sert',
    lore_short: 'Dünyanın en çok ödül alan İrlanda viskisi. Sadece İrlanda\\'ya özgü "Single Pot Still" (Maltlanmış ve maltlanmamış arpa karışımı) stiliyle üretilen kremamsı bir başyapıt.',
    lore_full: [
      { baslik: 'Köken', metin: '1900\\'lerin başında İngiliz vergi yasalarından kaçmak için maltlanmamış arpa kullanan İrlandalıların icat ettiği "Pot Still" tarzının bugün yaşayan en büyük temsilcisidir.' },
      { baslik: 'Yayılma', metin: 'İrlanda viskisi denince akla gelen Jameson veya Tullamore Dew gibi hafif harmanların ötesinde, kompleks bir İrlanda arayanların kült viskisidir.' },
      { baslik: 'Kültürel Etki', metin: 'İrlanda viskisinin İskoç maltlarıyla kafa kafaya yarışabileceğini hatta onları geçebileceğini kanıtlayan şişedir.' },
      { baslik: 'Modern Dönem', metin: 'Viski eleştirmenleri (Jim Murray vb.) tarafından defalarca "Yılın İrlanda Viskisi" seçilmiştir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Sınırlı sayıda gelir, tekel raflarından ziyade özel siparişle meraklıları tarafından bulunur.' }
    ],
    hammadde: 'Maltlanmış arpa ve maltlanmamış taze arpa karışımı.',
    uretim_sureci: 'Geleneksel İrlanda stili olan 3 kez (triple) bakır imbikte damıtma.',
    dinlendirme: '12 yıl; Oloroso Sherry (İspanyol) ve Bourbon fıçıları.',
    renk: 'Koyu altın, bakır.',
    koku: 'Kızarmış badem, şeri fıçısından gelen koyu meyveler, incir ve baharat.',
    tat: 'Maltlanmamış arpadan gelen inanılmaz kremamsı/yağlı bir gövde. Meyveli kek, fındık, zencefil ve meşe.',
    finish: 'Çok uzun, tatlımsı ve baharatlı.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Glencairn', sicaklik: 'Oda sıcaklığı', miktar: '40 ml', hazirlik: 'Sade.' },
    mix_detay: [],
    yiyecek: 'Kuru yemiş, karamelli tatlılar.',
    muzik_his: 'Folk, Klasik İrlanda.',
    mevsim: 'Kış',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 kadeh', ideal: '2 kadeh', limit_ustu: '3+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['Jameson Black Barrel'], orta_seviye: ['-'], premium: ['Redbreast 12', 'Redbreast 15'], fiyat_araligi: '2000 - 3000', nereden_alinir: 'Gurme mağazalar.', pop_kultur: 'Kuş lobisi (etiketindeki kızılgerdan kuşu).', yanlis_bilinenler: 'Tüm İrlanda viskileri hafif ve zayıftır algısını tek başına yıkar.', sozler: '"İrlanda\\'nın gerçek ruhu."'
  }`;

let content = fs.readFileSync('src/data/viski.js', 'utf-8');
content = content.replace(/\n\];/, `,\n${extraViski}\n];`);
fs.writeFileSync('src/data/viski.js', content);
console.log("3 Viski added.");
