const fs = require('fs');
const path = require('path');

const votkaPath = path.join(__dirname, 'src', 'data', 'votka.js');
const ronPath = path.join(__dirname, 'src', 'data', 'ron.js');

const votkas = `  {
    id: 'absolut',
    name: 'Absolut',
    emoji: '🧊',
    color: '#0048ce',
    aliases: ['Absolut Blue', 'İsveç Votkası'],
    origin: 'İsveç',
    ana_tur: 'votka',
    alt_tur: 'standart',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'hafif tahıl'],
    alkol_seviye: 'sert',
    lore_short: 'Dünyanın en ikonik şişesine sahip İsveç klasiği. Ahus kasabasında kışlık buğdaydan üretilir.',
    lore_full: [
      { baslik: 'Köken', metin: '1879\\'da Lars Olsson Smith tarafından "Absolut Rent Brännvin" (Kesinlikle Saf Votka) adıyla yaratıldı. Smith, sürekli damıtma yöntemini İsveç\\'e getirerek fusel alkolünü tamamen yok etmeyi başardı.' },
      { baslik: 'Modern Dönem', metin: '1979\\'da küresel pazara açılan marka, eski bir eczane şişesinden ilham alan tasarımıyla efsaneleşti. Pop-art ikonları Andy Warhol ve Keith Haring gibi sanatçılarla yaptığı işbirlikleriyle kültür tarihine kazındı.' }
    ],
    hammadde: 'Kışlık buğday ve saf kuyu suyu.',
    uretim_sureci: 'Sürekli damıtma ve kışlık buğday kullanımı.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Temiz, hafif buğday kokusu.',
    tat: 'Pürüzsüz, hafif tatlımsı ve buğday karakterli.',
    finish: 'Kısa, temiz.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot bardağı', sicaklik: 'Buzluktan çıkmış', miktar: '40 ml', hazirlik: 'Buz gibi shot.' },
    mix_detay: [
      { isim: 'Absolut Tonic', malzemeler: ['50 ml Absolut', 'Tonik', 'Limon dilimi'], hazirlanis: 'Buz dolu bardağa ekleyip karıştırın.', neden: 'Temiz karakteri toniği öne çıkarır.', ortam: 'Bar, ev partisi.' }
    ],
    yiyecek: 'Somon, meze tabakları.',
    muzik_his: 'Pop, elektronik.',
    mevsim: 'Her mevsim',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2 shot', ideal: '4 shot', limit_ustu: '6+ shot', ertesi_gun: 2 },
    etki_hizi: 'Hızlı',
    metabolizma: 'Hızlı',
    baslangic_onerileri: ['Absolut'],
    orta_seviye: ['Ketel One'],
    premium: ['Grey Goose'],
    fiyat_araligi: '600 - 900',
    nereden_alinir: 'Her yerde.',
    pop_kultur: 'Andy Warhol\\'un şişe tasarımıyla ünlenmiştir.',
    yanlis_bilinenler: 'İsveç dışında üretildiği sanılır ama her damlası Ahus kasabasından çıkar.',
    sozler: '"Absolut Perfection."'
  },
  {
    id: 'grey-goose',
    name: 'Grey Goose',
    emoji: '🦢',
    color: '#002663',
    aliases: ['Goose'],
    origin: 'Fransa',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sitrus', 'badem', 'çiçeksi'],
    alkol_seviye: 'sert',
    lore_short: 'Dünyanın ilk ultra-premium votkası. Fransız şıklığı ve kış buğdayının kusursuz uyumu.',
    lore_full: [
      { baslik: 'Köken', metin: 'Amerikalı iş adamı Sidney Frank tarafından 1997\\'de "dünyanın en iyi votkasını" yaratma vizyonuyla Fransa\\'nın Konyak bölgesinde doğdu. Maître de Chai (Kiler Ustası) François Thibault tarafından formüle edildi.' },
      { baslik: 'Kültürel Etki', metin: 'Lüks gece hayatının sembolü haline geldi. Şişenin içindeki kaz figürü, kalite ve statü arayanların anında tanıdığı bir simgeye dönüştü.' }
    ],
    hammadde: 'Picardie kış buğdayı ve Gensac kaynak suyu.',
    uretim_sureci: 'Konyak bölgesinin kireçtaşından süzülmüş suyla 5 kez damıtılır.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Hafif badem, sitrus ve çiçeksi notalar.',
    tat: 'Çok pürüzsüz, kremsi ve hafif badem tatlılığı.',
    finish: 'Uzun, temiz ve ferahlatıcı.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Martini kadehi', sicaklik: 'Soğuk', miktar: '50 ml', hazirlik: 'Buzlu çalkalanmış.' },
    mix_detay: [
      { isim: 'Grey Goose Martini', malzemeler: ['60 ml Grey Goose', '10 ml Kuru Vermut', 'Limon kabuğu'], hazirlanis: 'Buzla çalkalayıp soğutulmuş kadehe süzün.', neden: 'Votkanın çiçeksi dokusu martinide parlar.', ortam: 'Lüks lounge.' }
    ],
    yiyecek: 'Havyar, istiridye.',
    muzik_his: 'House, chill-out.',
    mevsim: 'Her mevsim',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Orta',
    metabolizma: 'Hızlı',
    baslangic_onerileri: ['Absolut'],
    orta_seviye: ['Belvedere'],
    premium: ['Grey Goose'],
    fiyat_araligi: '1500 - 2500',
    nereden_alinir: 'Premium barlar, tekel.',
    pop_kultur: 'Hip-hop liriklerinde lüks sembolü olarak sıkça geçer.',
    yanlis_bilinenler: 'Sadece pazarlama ürünü sanılır, oysa hammaddesi Fransa\\'nın en kaliteli buğdaylarındandır.',
    sozler: '"Fly beyond."'
  },
  {
    id: 'belvedere',
    name: 'Belvedere',
    emoji: '🍸',
    color: '#e5e5e5',
    aliases: ['Belvedere Votka'],
    origin: 'Polonya',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['vanilya', 'beyaz biber'],
    alkol_seviye: 'sert',
    lore_short: 'Dünyanın ilk lüks votkalarından biri. Saf Polonya çavdarı ve artizyen suyunun güçlü karakteri.',
    lore_full: [
      { baslik: 'Köken', metin: '1993\\'te piyasaya sürüldü. Adını Varşova\\'daki başkanlık sarayı Belweder\\'den alır. Üzerindeki ağaç çizimi o sarayın bahçesine aittir.' },
      { baslik: 'Modern Dönem', metin: 'LVMH grubu altında lüksün doruklarına ulaşmıştır. Çavdarın getirdiği baharatlı ve dolgun yapı, onu diğer buğday votkalarından ayırır.' }
    ],
    hammadde: 'Dankowskie çavdarı.',
    uretim_sureci: '4 kez damıtılır, hiçbir katkı veya şeker içermez.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Hafif vanilya ve kremamsı doku.',
    tat: 'Dolu bir yapı. Vanilya, badem ve beyaz karabiberin baharatlı vuruşu.',
    finish: 'Uzun, baharatlı ve sıcak.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Shot veya Rock', sicaklik: 'Soğuk', miktar: '40 ml', hazirlik: 'Sek veya tek buzla yudumlanarak.' },
    mix_detay: [
      { isim: 'Belvedere 007 Martini', malzemeler: ['60 ml Belvedere', '10 ml Kuru Vermut', 'Zeytin'], hazirlanis: 'Shakerda karıştır.', neden: 'Çavdarın karakteri, martiniye mükemmel bir "bite" katar.', ortam: 'Şık davetler.' }
    ],
    yiyecek: 'Steak, zengin soslu yemekler.',
    muzik_his: 'Jazz, klasik.',
    mevsim: 'Her mevsim',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Hızlı',
    metabolizma: 'Hızlı',
    baslangic_onerileri: ['Stolichnaya'],
    orta_seviye: ['Belvedere'],
    premium: ['Belvedere Single Estate'],
    fiyat_araligi: '1500 - 2500',
    nereden_alinir: 'Lüks içki mağazaları.',
    pop_kultur: 'Spectre filminde James Bond\\'un resmi içkisi.',
    yanlis_bilinenler: 'Tüm lüks votkalar yumuşaktır sanılır, Belvedere çavdardan dolayı bilerek baharatlıdır.',
    sozler: '"Know the difference."'
  },
  {
    id: 'stolichnaya',
    name: 'Stolichnaya',
    emoji: '🔴',
    color: '#d32f2f',
    aliases: ['Stoli'],
    origin: 'Rusya / Letonya',
    ana_tur: 'votka',
    alt_tur: 'standart',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['sek', 'karabiber', 'tahıl'],
    alkol_seviye: 'sert',
    lore_short: 'Sovyetlerin dünyaya armağanı, uzaya çıkan ilk votka markası. Klasik, maskülen ve sağlam bir karakter.',
    lore_full: [
      { baslik: 'Köken', metin: '1901\\'de kurulan Moskova Devlet Şarap Deposu No.1\\'de doğdu. "Stolichnaya", başkent (Moskova) anlamına gelir. 1970\\'lerde Pepsi ile yapılan tarihi bir takas anlaşmasıyla ABD\\'ye giren ilk Sovyet votkası oldu.' },
      { baslik: 'Kültürel Etki', metin: 'Tarihin en çok bilinen Rus votkası. Ancak günümüzde mülkiyet tartışmaları nedeniyle bir kısmı Rusya, bir kısmı Letonya üretimidir.' }
    ],
    hammadde: 'Buğday ve çavdar.',
    uretim_sureci: 'Geleneksel olarak kuvars kumu ve huş ağacı kömüründen filtrelenir.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Taze tahıl, mineral ve çok hafif narenciye.',
    tat: 'Pürüzsüz ama karakterli, orta damakta anason ve karabiber dokunuşları.',
    finish: 'Sıcak, temiz ve baharatlı.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot', sicaklik: 'Buzluktan çıkmış', miktar: '40 ml', hazirlik: 'Klasik Rus shot stili.' },
    mix_detay: [
      { isim: 'White Russian', malzemeler: ['40 ml Stoli', '20 ml Kahve Likörü', 'Krema'], hazirlanis: 'Buzlu bardağa sırayla ekle.', neden: 'Stoli\\'nin karakteri kahve likörünün tatlılığını dengeler.', ortam: 'Bowling salonu, rahat bar.' }
    ],
    yiyecek: 'Turşu, rus salatası, siyah ekmek.',
    muzik_his: 'Rock, retro.',
    mevsim: 'Kış',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2 shot', ideal: '4 shot', limit_ustu: '6+ shot', ertesi_gun: 3 },
    etki_hizi: 'Çok hızlı',
    metabolizma: 'Hızlı',
    baslangic_onerileri: ['Smirnoff'],
    orta_seviye: ['Stoli'],
    premium: ['Stoli Elit'],
    fiyat_araligi: '600 - 900',
    nereden_alinir: 'Tekel, market.',
    pop_kultur: 'The Big Lebowski\\'deki efsanevi White Russian\\'ın baş aktörü.',
    yanlis_bilinenler: 'Tümüyle Rus sanılır, ama global satılan Stoli\\'lerin çoğu Letonya\\'da şişelenir.',
    sozler: '"The original."'
  },
  {
    id: 'ketel-one',
    name: 'Ketel One',
    emoji: '⚗️',
    color: '#8c7355',
    aliases: ['Ketel'],
    origin: 'Hollanda',
    ana_tur: 'votka',
    alt_tur: 'premium',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['rezene', 'narenciye'],
    alkol_seviye: 'sert',
    lore_short: 'Barmenlerin favorisi, Hollandalı Nolet ailesinin bakır imbiklerle damıttığı karakterli premium votka.',
    lore_full: [
      { baslik: 'Köken', metin: 'Hollanda\\'daki Nolet damıtımevi 1691\\'den beri faaliyet göstermektedir. Ketel One, adını hala kullanılan 1 numaralı bakır imbikten (Distilleerketel #1) alır.' },
      { baslik: 'Modern Dönem', metin: 'Dünyanın en iyi barlarında en çok tavsiye edilen votkalardan biridir. Sanayi tipi dev üretimlerden ziyade aile mirasını ve artizanal damıtmayı öne çıkarır.' }
    ],
    hammadde: 'Avrupa kış buğdayı.',
    uretim_sureci: 'Modern kolon damıtma ile geleneksel bakır imbik (pot still) damıtmasının harmanlanması.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Taze, temiz, hafif narenciye ve bal özü.',
    tat: 'Pürüzsüz, rezene ve anason dokunuşlarıyla hafif karıncalanma.',
    finish: 'Uzun ve canlı.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Martini', sicaklik: 'Soğuk', miktar: '50 ml', hazirlik: 'Sek içime uygun.' },
    mix_detay: [
      { isim: 'Ketel One Bloody Mary', malzemeler: ['50 ml Ketel One', 'Domates Suyu', 'Baharatlar'], hazirlanis: 'Bol baharatla karıştır.', neden: 'Bakır imbik karakteri baharatlarla eşsiz uyum sağlar.', ortam: 'Pazar brunch\\'ı.' }
    ],
    yiyecek: 'Kahvaltı tabakları, brunch.',
    muzik_his: 'Akustik, lo-fi.',
    mevsim: 'İlkbahar',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2 kadeh', ideal: '4 kadeh', limit_ustu: '5+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Orta',
    metabolizma: 'Hızlı',
    baslangic_onerileri: ['Ketel One'],
    orta_seviye: ['Belvedere'],
    premium: ['Grey Goose'],
    fiyat_araligi: '1000 - 1500',
    nereden_alinir: 'Özel tekel ve barlar.',
    pop_kultur: 'Dünya miksoloji yarışmalarının (World Class) demirbaşıdır.',
    yanlis_bilinenler: 'Hollanda sadece cin (jenever) yapar sanılır, Ketel One bunu yıkan markadır.',
    sozler: '"Gentlemen, this is vodka."'
  }`;

const romlar = `  {
    id: 'malibu',
    name: 'Malibu',
    emoji: '🥥',
    color: '#ffffff',
    aliases: ['Hindistan Cevizi Romu'],
    origin: 'Barbados',
    ana_tur: 'ron',
    alt_tur: 'flavoured',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['hindistan cevizi', 'şeker', 'vanilya'],
    alkol_seviye: 'hafif',
    lore_short: 'Dünyanın en bilinen hindistan cevizi aromalı rom likörü. Tatili ve kumsalı anında kadehe getiren ikonik beyaz şişe.',
    lore_full: [
      { baslik: 'Köken', metin: '1982\\'de aslen Piña Colada yapımını kolaylaştırmak için icat edildi. Başlangıçta Curaçao\\'da meyve aromalarıyla karıştırılan romlardan ilham alındı, daha sonra üretim Barbados\\'taki West Indies Rum Distillery\\'ye taşındı.' },
      { baslik: 'Kültürel Etki', metin: 'Sert içkilerden hoşlanmayanlar ve tatlı kokteyl sevenler için mükemmel bir giriş kapısıdır. Popüler tatil beldelerinin vazgeçilmez içkisidir.' }
    ],
    hammadde: 'Barbados romu, doğal hindistan cevizi aroması ve şeker.',
    uretim_sureci: 'Geleneksel olarak damıtılmış beyaz romun hindistan cevizi özütü ve şekerle harmanlanması.',
    dinlendirme: 'Dinlendirilmez.',
    renk: 'Tamamen şeffaf.',
    koku: 'Yoğun, tatlı hindistan cevizi, güneş kremi ve vanilya.',
    tat: 'Çok tatlı, şurup kıvamında, belirgin hindistan cevizi ve badem ezmesi.',
    finish: 'Kısa, çok tatlı ve hindistan cevizi baskın.',
    vucut: 'Light body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot', sicaklik: 'Çok soğuk', miktar: '40 ml', hazirlik: 'Çok tercih edilmez ama buzlu içilebilir.' },
    mix_detay: [
      { isim: 'Malibu Pineapple', malzemeler: ['50 ml Malibu', '100 ml Ananas Suyu', 'Buz'], hazirlanis: 'Bardağa buz doldurup karıştırın.', neden: 'Piña Colada lezzetini zahmetsizce verir.', ortam: 'Plaj partisi, havuz başı.' }
    ],
    yiyecek: 'Tropikal meyveler, dondurma.',
    muzik_his: 'Reggae, tropikal pop.',
    mevsim: 'Yaz',
    abv_range: '21',
    standart_porsiyon: '50',
    kafa_dozu: { hafif: '2-3 kadeh', ideal: '5 kadeh', limit_ustu: '7+ kadeh', ertesi_gun: 4 },
    etki_hizi: 'Yavaş',
    metabolizma: 'Yavaş',
    baslangic_onerileri: ['Malibu'],
    orta_seviye: ['Captain Morgan'],
    premium: ['Bumbu'],
    fiyat_araligi: '500 - 750',
    nereden_alinir: 'Her yerde.',
    pop_kultur: '"Malibu Beach" yaşam tarzının şişelenmiş halidir.',
    yanlis_bilinenler: 'Gerçek bir rom sanılır ancak teknik olarak %21 alkol oranı ve yüksek şekeriyle bir rom likörüdür.',
    sozler: '"Let the summer begin."'
  },
  {
    id: 'zacapa-23',
    name: 'Ron Zacapa Centenario 23',
    emoji: '🍯',
    color: '#8b4513',
    aliases: ['Zacapa', 'Zacapa 23'],
    origin: 'Guatemala',
    ana_tur: 'ron',
    alt_tur: 'aged',
    gorunum: 'koyu_amber',
    olgunlasma: 'solera',
    aroma: ['bal', 'karamel', 'çikolata', 'kuru üzüm'],
    alkol_seviye: 'sert',
    lore_short: 'Bulutların üzerinde olgunlaşan rom. Deniz seviyesinden 2300 metre yüksekte solera sistemiyle yıllanan bir başyapıt.',
    lore_full: [
      { baslik: 'Köken', metin: '1976\\'da Zacapa şehrinin 100. yılını kutlamak için yaratıldı. Şişesindeki el örgüsü hasır (petate), Maya krallarının tahtlarında kullandıkları örgüdür.' },
      { baslik: 'Üretim Sırrı', metin: 'Normal romların aksine melastan değil, "sugar cane virgin honey" denilen şeker kamışı balından üretilir. Dağların serin havasında, daha yavaş ve dengeli yaşlanarak muazzam bir zenginlik kazanır.' }
    ],
    hammadde: 'Şeker kamışı balı (virgin sugar cane honey).',
    uretim_sureci: 'Solera sistemiyle, eskiden Amerikan viskisi, şeri ve Pedro Ximénez şarabı barındırmış fıçılarda harmanlanarak yaşlandırılır.',
    dinlendirme: '6 ile 23 yıl arası yaşlanmış romların solera harmanı.',
    renk: 'Koyu maun, altın yansımalar.',
    koku: 'Karamel, kakao, kızarmış fındık ve pekmez.',
    tat: 'Çok yoğun, tatlı ve kompleks. Bal, karamelize meyveler, badem ezmesi ve çikolata.',
    finish: 'Çok uzun, zarif ve pekmezli.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Snifter', sicaklik: 'Oda sıcaklığı', miktar: '40 ml', hazirlik: 'Sek veya tek bir büyük buz ile yavaşça.' },
    mix_detay: [
      { isim: 'Zacapa Old Fashioned', malzemeler: ['50 ml Zacapa 23', 'Esmer şeker', 'Çikolata Bitteri'], hazirlanis: 'Buzla yavaşça karıştır.', neden: 'Lüks ve tatlı bir kokteyl deneyimi.', ortam: 'Zengin bir akşam yemeği sonrası.' }
    ],
    yiyecek: 'Lüks çikolata, ağır purolar.',
    muzik_his: 'Klasik, senfonik, jazz.',
    mevsim: 'Kış',
    abv_range: '40',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 kadeh', ideal: '2 kadeh', limit_ustu: '3+ kadeh', ertesi_gun: 3 },
    etki_hizi: 'Orta',
    metabolizma: 'Orta',
    baslangic_onerileri: ['Diplomatico Reserva'],
    orta_seviye: ['Zacapa 23'],
    premium: ['Zacapa XO'],
    fiyat_araligi: '2500 - 3500',
    nereden_alinir: 'Lüks tekel ve duty free.',
    pop_kultur: 'Romların "Konyak"ı olarak anılır.',
    yanlis_bilinenler: 'İçindeki her damlanın 23 yıllık olduğu sanılır; Solera sisteminde 6 ile 23 yıl arası romların karışımıdır.',
    sozler: '"Aged above the clouds."'
  },
  {
    id: 'kraken',
    name: 'The Kraken Black Spiced Rum',
    emoji: '🦑',
    color: '#000000',
    aliases: ['Kraken', 'Black Rum'],
    origin: 'Trinidad ve Tobago',
    ana_tur: 'ron',
    alt_tur: 'spiced',
    gorunum: 'siyah',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['karanfil', 'tarçın', 'karamel', 'zencefil'],
    alkol_seviye: 'sert',
    lore_short: 'Karanlık, gizemli ve güçlü. Adını efsanevi deniz canavarı Kraken\\'den alan bu siyah baharatlı rom, sert ve yoğun bir macera sunuyor.',
    lore_full: [
      { baslik: 'Köken', metin: 'Karayipler\\'de damıtılıp 11 farklı gizli baharatla harmanlanır. Hikayesine göre, efsanevi deniz canavarı Kraken\\'in saldırdığı bir gemiden sağ kurtulan tek şey bu siyah rom fıçıları olmuştur.' },
      { baslik: 'Kültürel Etki', metin: 'Viktorya dönemi tasarımlı çift kulplu şişesi ve gotik pazarlamasıyla kısa sürede kültleşti. "Release the Kraken" sloganıyla alternatif ve rock/metal kültürü arasında çok tutuldu.' }
    ],
    hammadde: 'Melas ve 11 gizli baharat.',
    uretim_sureci: 'Damıtılmış roma baharat özütleri ve karamel eklenerek rengi ve tadı yoğunlaştırılır.',
    dinlendirme: '1-2 yıl fıçıda dinlenir.',
    renk: 'Simsiyah, mürekkep koyusu.',
    koku: 'Yoğun vanilya, espresso, karanfil ve tarçın.',
    tat: 'Koyu karamel, baharat patlaması, zencefil, pekmez ve karanfil.',
    finish: 'Uzun, baharatlı, tatlı ama yakıcı.',
    vucut: 'Full body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Shot', sicaklik: 'Soğuk', miktar: '40 ml', hazirlik: 'Cesaret isteyen sert bir shot.' },
    mix_detay: [
      { isim: 'Kraken & Cola', malzemeler: ['50 ml Kraken', 'Kola', 'Lime'], hazirlanis: 'Buzlu bardağa ekle.', neden: 'Baharatlar kolanın asiditesini muazzam destekler.', ortam: 'Rock bar, gece geç saatler.' }
    ],
    yiyecek: 'Barbekü etler, baharatlı atıştırmalıklar.',
    muzik_his: 'Rock, metal, karanlık atmosferler.',
    mevsim: 'Sonbahar ve Kış',
    abv_range: '40',
    standart_porsiyon: '50',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 4 },
    etki_hizi: 'Hızlı',
    metabolizma: 'Orta',
    baslangic_onerileri: ['Captain Morgan Black'],
    orta_seviye: ['The Kraken'],
    premium: ['Goslings Black Seal'],
    fiyat_araligi: '900 - 1300',
    nereden_alinir: 'Tekel, online.',
    pop_kultur: 'Korsan mitolojisi ve gotik estetikte zirvedir.',
    yanlis_bilinenler: 'Kötü romun rengini kararttıkları sanılır, oysa kendi tarzında ustaca yapılmış bir baharat bombasıdır.',
    sozler: '"Release the Kraken!"'
  }`;

let vContent = fs.readFileSync(votkaPath, 'utf8');
let rContent = fs.readFileSync(ronPath, 'utf8');

vContent = vContent.replace(/,\\s*\\n\\];/, '\\n];');
vContent = vContent.replace(/\\n\\];/, ',\\n' + votkas + '\\n];');

rContent = rContent.replace(/,\\s*\\n\\];/, '\\n];');
rContent = rContent.replace(/\\n\\];/, ',\\n' + romlar + '\\n];');

fs.writeFileSync(votkaPath, vContent, 'utf8');
fs.writeFileSync(ronPath, rContent, 'utf8');
console.log('Veriler başarıyla eklendi.');
