const fs = require('fs');

const extraRakis = `  {
    id: 'beylerbeyi-gobek',
    name: 'Beylerbeyi Göbek',
    emoji: '🥃',
    color: '#e6f2ff',
    aliases: ['Beylerbeyi'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'göbek',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'pürüzsüz'],
    alkol_seviye: 'sert',
    lore_short: 'Modern meyhanenin prestij sembolü. 3 kez damıtılan sumanın göbek kesimi ve sıfır ilave şeker. En sek, en saf ve yeni neslin favori rakılarından biri.',
    lore_full: [
      { baslik: 'Köken', metin: 'Sarper İçecek tarafından Akhisar Manisa\\'da üretilmeye başlanan Beylerbeyi, özellikle Göbek versiyonu ile rakı dünyasında ezber bozdu. %100 yaş üzüm sumasından ve anasondan üretilir.' },
      { baslik: 'Yayılma', metin: 'Özellikle İstanbul\\'daki lüks meyhanelerde ve yeni nesil balıkçılarda "Masanın hakkı Beylerbeyi" mottosuyla hızla yayıldı.' },
      { baslik: 'Kültürel Etki', metin: 'İlave şeker içermediği için (0 gram) ertesi gün baş ağrısı yapmadığı inancı (ki bu suma saflığıyla da ilgilidir) onu çok popüler yaptı.' },
      { baslik: 'Modern Dönem', metin: 'Göbek rakısı trendini ana akıma taşıyan markalardan biridir. Şişe tasarımı ve marka algısı çok yüksektir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Genç neslin ve daha "premium" bir deneyim arayanların ilk tercihlerinden.' }
    ],
    hammadde: 'Ege bölgesi yaş üzümleri, Kalınkara anasonu.',
    uretim_sureci: 'Suma 3 kez damıtılır, sadece orta kesim (göbek) kullanılır. İlave tarımsal etil alkol ve şeker sıfırdır.',
    dinlendirme: 'Çelik tanklarda.',
    renk: 'Sek iken şeffaf, su eklendiğinde parlak beyaz.',
    koku: 'Saf ve temiz anason.',
    tat: 'Şeker olmamasına rağmen yaş üzümden gelen doğal bir meyvemsi tatlılık, çok yumuşak bir içim.',
    finish: 'Uzun, pürüzsüz, kadife gibi.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Ehlikeyf', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Klasik Rakı Su', malzemeler: ['1 ölçü Rakı', '1 ölçü Su', 'Buz'], hazirlanis: 'Sırasıyla konur.', neden: 'Göbek yapısı suyu çok iyi taşır.', ortam: 'Yeni nesil meyhane.' } ],
    yiyecek: 'Ahtapot ızgara, karides mantı, avokadolu mezeler.',
    muzik_his: 'Modern Türkçe Pop, Akustik.',
    mevsim: 'Her mevsim',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '2 duble', ideal: '4 duble', limit_ustu: '5+ duble', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['Beylerbeyi Terapi'], orta_seviye: ['Beylerbeyi Göbek'], premium: ['Beylerbeyi Mavi'], fiyat_araligi: '1000 - 1500', nereden_alinir: 'Tekeller, marketler.', pop_kultur: 'Şekersiz rakı akımının yıldızı.', yanlis_bilinenler: 'Şekersiz olduğu için acı sanılır, yaş üzüm onu yumuşatır.', sozler: '"Şekersiz, saf ve öz."'
  },
  {
    id: 'yeni-raki-yas-uzum',
    name: 'Yeni Rakı Yaş Üzüm',
    emoji: '🍇',
    color: '#e0f7e9',
    aliases: ['Yeni Seri', 'Yaş Üzüm'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'yaş_üzüm',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'meyvemsi'],
    alkol_seviye: 'sert',
    lore_short: 'Taze kesilmiş üzüm bağlarının şişelenmiş hali. Kuru üzüm yerine hasat edilmiş taze üzümlerden üretilen, daha meyvemsi ve aromatik bir Klasik.',
    lore_full: [
      { baslik: 'Köken', metin: 'Geleneksel olarak rakı kuru üzümden yapılırdı (saklanması kolay olduğu için). Yaş üzüm rakıları ise hasat zamanı elde edilen taze üzümlerin fermente edilmesiyle üretilir.' },
      { baslik: 'Yayılma', metin: 'Özellikle son 15 yılda yaş üzüm rakılarına olan talep, damak tadının daha meyvemsi profillere kaymasıyla arttı.' },
      { baslik: 'Kültürel Etki', metin: 'Klasik Yeni Rakı\\'nın ağırlığından ziyade daha neşeli, daha baharatsız, çiçeksi bir deneyim sunar.' },
      { baslik: 'Modern Dönem', metin: 'Yeni Seri adıyla piyasaya sürüldüğünde devasa bir pazar payı yakaladı.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Bahar aylarında, Ege kıyılarında zeytinyağlı mezelerle eşleşmenin bir numarasıdır.' }
    ],
    hammadde: 'Taze yaş üzüm, Anason.',
    uretim_sureci: 'Taze üzüm şırasından elde edilen suma, anasonla damıtılır.',
    dinlendirme: 'Çelik tank.',
    renk: 'Berrak, suyla parlak beyaz.',
    koku: 'Taze üzüm, anason ve kır çiçekleri.',
    tat: 'Meyvemsi, daha tatlımsı, damakta canlı.',
    finish: 'Canlandırıcı ve kısa-orta.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: 'Yok', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Rakı Su', malzemeler: ['1 ölçü Rakı', '1 ölçü Su', 'Buz'], hazirlanis: 'Klasik', neden: 'Ferahlık için', ortam: 'Gündüz rakısı, yaz sofrası.' } ],
    yiyecek: 'Zeytinyağlılar, enginar, deniz börülcesi.',
    muzik_his: 'Ege türküleri, neşeli pop.',
    mevsim: 'İlkbahar ve Yaz',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1-2 duble', ideal: '3-4 duble', limit_ustu: '5+ duble', ertesi_gun: 3 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['-'], orta_seviye: ['Yeni Seri'], premium: ['-'], fiyat_araligi: '800 - 1200', nereden_alinir: 'Her yerde.', pop_kultur: 'Kavunla en çok yakıştırılan rakılardan.', yanlis_bilinenler: 'Kuru üzümden daha az alkollü sanılır, alakası yoktur.', sozler: '"Taze üzüm, taze başlangıçlar."'
  },
  {
    id: 'sarisin-yas-uzum',
    name: 'Sarışın Yaş Üzüm',
    emoji: '🥂',
    color: '#fffae6',
    aliases: ['Sarışın'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'yaş_üzüm',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'misket üzümü'],
    alkol_seviye: 'sert',
    lore_short: 'Sadece Bornova Misketi üzümünden üretilen butik bir devrim. Çiçeksi, buram buram meyve kokan, çok özel bir yaş üzüm rakısı.',
    lore_full: [
      { baslik: 'Köken', metin: 'Sadece tek bir üzüm türünden (Single Grape) rakı yapma vizyonuyla doğdu. Bornova Misketi, dünyanın en aromatik üzümlerinden biridir.' },
      { baslik: 'Yayılma', metin: 'Sınırlı üretim olduğu için (Small Batch) sadece belirli mahzenlerde ve üst düzey restoranlarda bulunur.' },
      { baslik: 'Kültürel Etki', metin: 'Rakıda terroir (toprak/bölge karakteri) kavramını Türkiye\\'de en iyi hissettiren ürünlerden biridir.' },
      { baslik: 'Modern Dönem', metin: 'Özel şişesi ve sarımtırak etiketiyle "wine-lover" (şarap sever) kitlenin rakı dünyasındaki sığınağıdır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Gastronomi tutkunlarının ve şeflerin tadım menülerinde tercihidir.' }
    ],
    hammadde: '%100 Bornova Misketi yaş üzüm, Ege anasonu.',
    uretim_sureci: 'Misket üzümü şırasından düşük ısıda yavaş damıtma.',
    dinlendirme: 'Çelik tank.',
    renk: 'Su eklendiğinde daha gümüşi bir beyaz.',
    koku: 'Misket üzümünün o karakteristik çiçek (ıtır, gül) ve egzotik meyve kokuları anasonun önüne geçer.',
    tat: 'Müthiş aromatik, tatlımsı, meyveli ve çok yumuşak.',
    finish: 'Uzun, çiçeksi ve parfüm gibi.',
    vucut: 'Light to Medium',
    rakon: 'mix',
    sek_detay: { kadeh: '', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Aromatik Rakı', malzemeler: ['1 ölçü Sarışın', '0.5 ölçü Su'], hazirlanis: 'Çok az su eklenmesi tavsiye edilir, aromalar kaybolmasın diye.', neden: 'Misket üzümünün narin yapısı çok su kaldırmaz.', ortam: 'Tadım gecesi.' } ],
    yiyecek: 'Sushi, hafif peynirler, meyve tabakları.',
    muzik_his: 'Caz, Akustik.',
    mevsim: 'İlkbahar',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 duble', ideal: '2 duble', limit_ustu: '4+ duble', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Sarışın'], fiyat_araligi: '1500 - 2500', nereden_alinir: 'Butik tekeller.', pop_kultur: 'Koleksiyonerlerin gözdesi.', yanlis_bilinenler: 'Sarışın dendiği için renginin sarı olduğu sanılır; içki şeffaftır, üzümü beyazdır.', sozler: '"Şarabın rakı hali."'
  },
  {
    id: 'bleu-caravan',
    name: 'Bleu Caravan',
    emoji: '🚐',
    color: '#e6f0ff',
    aliases: ['Bleu'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'butik',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'zengin'],
    alkol_seviye: 'sert',
    lore_short: 'Türkiye\\'nin ilk gerçek "Craft" (Zanaatkar) rakılarından. Küçük bakır imbiklerde, her partisi (batch) özenle numaralandırılmış, endüstriyel olmayan bir başyapıt.',
    lore_full: [
      { baslik: 'Köken', metin: 'Endüstriyel rakı üretimine bir tepki olarak, geleneksel aile reçetelerine dönüş felsefesiyle kuruldu.' },
      { baslik: 'Yayılma', metin: 'Sadece butik mağazalarda, niş miksoloji barlarında ve özel restoranlarda yer aldı.' },
      { baslik: 'Kültürel Etki', metin: 'Türkiye\\'de içki kültürünün "az ama öz içmek" mottosunu rakı kategorisine taşıdı.' },
      { baslik: 'Modern Dönem', metin: 'Şişe tasarımı, etiket kalitesi ve hikayeciliği ile "Hipster" rakısı olarak da tanımlanabilir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Rakı koleksiyonerlerinin raflarında şişesi mutlaka saklanır.' }
    ],
    hammadde: 'Seçme yaş üzümler, yüksek kalite anason.',
    uretim_sureci: 'Küçük bakır imbiklerde (Alembic) yavaş ve partiler halinde (Small Batch) damıtma.',
    dinlendirme: 'Dinlendirilmiş (tankta).',
    renk: 'Berrak.',
    koku: 'Kompleks, zengin anason ve arka planda hafif narenciye.',
    tat: 'Dolu dolu, zengin dokulu, alkol yanmasını hissettirmeyen yağlı bir yapı.',
    finish: 'Çok uzun ve tatminkar.',
    vucut: 'Full body',
    rakon: 'mix',
    sek_detay: { kadeh: '', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Craft Rakı', malzemeler: ['Rakı', 'Su'], hazirlanis: 'Sadece kaliteli şişe suyu ile.', neden: 'Mineralli sular rakının yapısını bozabilir.', ortam: 'Yakın dostlarla özel bir kutlama.' } ],
    yiyecek: 'Artizan peynirler, carpaccio, gurme mezeler.',
    muzik_his: 'Indie, Lo-Fi, Alternatif Rock.',
    mevsim: 'Sonbahar',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 duble', ideal: '3 duble', limit_ustu: '4+ duble', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Bleu Caravan'], fiyat_araligi: '1600 - 2500', nereden_alinir: 'Özel gurme marketler.', pop_kultur: 'Sanatçı tayfanın yeni favorisi.', yanlis_bilinenler: 'Fransız markası sanılır (isminin bleu olmasından), tamamen Türk üretimidir.', sozler: '"Zanaatın tadı."'
  },
  {
    id: 'sabuhi',
    name: 'Sabuhi',
    emoji: '🏺',
    color: '#ffffff',
    aliases: ['Sabûhî'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'butik',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'geleneksel'],
    alkol_seviye: 'sert',
    lore_short: 'Divan edebiyatından kopup gelen, sabahın ilk ışıklarıyla içilen efsanevi şarabın ruhu, butik bir rakıda yeniden canlanıyor. Limitli, yöresel ve son derece otantik.',
    lore_full: [
      { baslik: 'Köken', metin: 'Sabuhi, Osmanlıca ve Farsçada "sabah içilen şarap" veya "sabah aydınlığı" anlamına gelir. Eski meyhanecilik geleneğini diriltme amacıyla yaratılmış butik bir projedir.' },
      { baslik: 'Yayılma', metin: 'Sadece bilenlerin bildiği, kulaktan kulağa yayılan gizli bir hazine gibidir.' },
      { baslik: 'Kültürel Etki', metin: 'Rakının sadece endüstriyel bir tüketim nesnesi değil, şiirsel bir obje olabileceğini kanıtlar.' },
      { baslik: 'Modern Dönem', metin: 'Etiketindeki divan esintileri ve özel reçetesiyle saygı uyandırır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Tarih, edebiyat ve gastronomi meraklılarının masalarını süsler.' }
    ],
    hammadde: 'Özel yöre üzümleri, organik anason.',
    uretim_sureci: 'Geleneksel küçük imbik damıtması.',
    dinlendirme: 'Kısa süre.',
    renk: 'Beyaz.',
    koku: 'Mistik, hafif baharatlı yoğun anason.',
    tat: 'Eski zaman rakıları gibi karakterli, damakta iz bırakan, hafif acımsı/baharatlı gerçek bir klasik yapı.',
    finish: 'Kalıcı ve güçlü.',
    vucut: 'Full body',
    rakon: 'mix',
    sek_detay: { kadeh: '', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Geleneksel Su', malzemeler: ['Rakı', 'Su'], hazirlanis: 'Buzsuz içimi tavsiye edilir.', neden: 'Buz aromaları kilitler.', ortam: 'Tarihi bir köşk, edebiyat sohbeti.' } ],
    yiyecek: 'Ağır et yemekleri, lakerda, pastırma.',
    muzik_his: 'Klasik Türk Müziği, Ney taksimleri.',
    mevsim: 'Kış',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 duble', ideal: '2 duble', limit_ustu: '3+ duble', ertesi_gun: 3 },
    etki_hizi: 'Hızlı', metabolizma: 'Yavaş', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Sabuhi'], fiyat_araligi: '1400 - 2000', nereden_alinir: 'Gurme mağazalar.', pop_kultur: 'Edebiyatçıların sırrı.', yanlis_bilinenler: 'Eski TEKEL rakılarından sanılır, yeni nesil craft bir markadır.', sozler: '"Sabah aydınlığı."'
  },
  {
    id: 'taris-yas-uzum',
    name: 'Tariş Yaş Üzüm',
    emoji: '🍇',
    color: '#e6f7ff',
    aliases: ['Tariş'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'yaş_üzüm',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['anasonlu', 'üzüm'],
    alkol_seviye: 'sert',
    lore_short: 'Ege çiftçisinin emeği, kooperatif dayanışmasının şişedeki hali. Kendi bağlarının üzümünü kendi işleyen, mütevazı ama dürüst bir Ege rakısı.',
    lore_full: [
      { baslik: 'Köken', metin: 'Tariş, Türkiye\\'nin en köklü tarım satış kooperatifidir. Zeytinyağı ve incirden sonra, bölgedeki üzüm üreticilerinin mahsullerini değerlendirmek için alkol pazarına da girmiştir.' },
      { baslik: 'Yayılma', metin: 'Özellikle Ege bölgesinde "çiftçinin kendi malı" olduğu için lokal bir milliyetçilikle çok sevilir.' },
      { baslik: 'Kültürel Etki', metin: 'Ucuz fiyat politikası gütmeden, dürüst ve temiz bir rakı yapma çabasıdır.' },
      { baslik: 'Modern Dönem', metin: 'Pazardaki büyük devlere karşı bir alternatif arayan yöre halkının tercihidir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'İzmir ve çevresinde market raflarında mutlaka kendine yer bulur.' }
    ],
    hammadde: 'Tariş kooperatifi yaş üzümleri, Ege anasonu.',
    uretim_sureci: 'Standart rakı damıtması.',
    dinlendirme: 'Çelik tank.',
    renk: 'Bulutlu beyaz.',
    koku: 'Taze yaş üzüm şırası ve temiz anason.',
    tat: 'İçimi kolay, şekeri dengeli, yumuşak ve arkadaş canlısı.',
    finish: 'Orta uzunlukta.',
    vucut: 'Medium body',
    rakon: 'mix',
    sek_detay: { kadeh: '', sicaklik: '', miktar: '', hazirlik: '' },
    mix_detay: [ { isim: 'Ege Usulü', malzemeler: ['Rakı', 'Soğuk Su'], hazirlanis: 'Buzlu', neden: 'Ege sıcaklarında ferahlık şart.', ortam: 'Köy kahvesi, deniz kenarı yazlık.' } ],
    yiyecek: 'Zeytin, zeytinyağlı tabağı, peynir.',
    muzik_his: 'Ege türküleri.',
    mevsim: 'Yaz',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1-2 duble', ideal: '3 duble', limit_ustu: '5+ duble', ertesi_gun: 3 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['-'], orta_seviye: ['Tariş Yaş Üzüm'], premium: ['-'], fiyat_araligi: '700 - 950', nereden_alinir: 'Tariş mağazaları, Ege tekelleri.', pop_kultur: 'Kooperatifçiliğin alkoldeki yüzü.', yanlis_bilinenler: 'Sadece zeytinyağı markası sanılır.', sozler: '"Topraktan kadehe."'
  },
  {
    id: 'efe-mese-fici',
    name: 'Efe Meşe Fıçı',
    emoji: '🪵',
    color: '#e6c280',
    aliases: ['Efe Meşe'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'meşe_fıçı',
    gorunum: 'sarımtırak',
    olgunlasma: 'fıçılanmış',
    aroma: ['anasonlu', 'meşe', 'vanilya'],
    alkol_seviye: 'sert',
    lore_short: 'Rakı ile viskinin sınırlarında gezen melez bir deneyim. Meşe fıçılarda dinlenerek altın rengini ve vanilya notalarını alan, rakıya yeni bir boyut katan devrimci bir adım.',
    lore_full: [
      { baslik: 'Köken', metin: 'Geleneksel olarak rakı fıçıda bekletilse de renk almadan şişelenirdi. Efe, Fransız meşe fıçılarında rakıyı 120 gün bekletip o kehribar rengiyle şişeleyerek bir tabuları yıktı.' },
      { baslik: 'Yayılma', metin: 'Viski ve konyak severlerin rakıya geçiş kapısı oldu.' },
      { baslik: 'Kültürel Etki', metin: 'Rakının "su katılınca beyazlar" kuralını esnetti, sek içime veya sadece buzla içime (on the rocks) uygun hale getirdi.' },
      { baslik: 'Modern Dönem', metin: 'İnovatif rakı kategorisinin öncüsü oldu.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Yemekle değil, yemek sonrasında puro veya çikolata ile eşleştirilen ilk rakılardan oldu.' }
    ],
    hammadde: 'Üzüm suması, anason, meşe fıçı ekstraktı.',
    uretim_sureci: 'Damıtma sonrası Fransız meşe fıçılarında dinlendirme.',
    dinlendirme: '120 gün meşe fıçılarda.',
    renk: 'Sek iken altın sarısı/kehribar. Su eklendiğinde sarımtırak-beyaz.',
    koku: 'Anasonun arkasından net bir şekilde meşe, vanilya ve karamel.',
    tat: 'Pürüzsüz, meşeden gelen yuvarlak bir tatlılık ve hafif isli-odunsu dokunuşlar.',
    finish: 'Viskiyi andıran, sıcak ve uzun.',
    vucut: 'Medium body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Rock glass (Viski kadehi)', sicaklik: 'Soğuk (Buzlu)', miktar: '50 ml', hazirlik: 'Sadece büyük bir buz kübü ile.' },
    mix_detay: [ { isim: 'Az Sulu', malzemeler: ['Rakı', 'Çok az su'], hazirlanis: 'Fıçı aromasını bozmamak için az su.', neden: 'Meşe notaları fazla suda kaybolur.', ortam: 'Şömine başı, yemek sonrası.' } ],
    yiyecek: 'Izgara etler, puro, bitter çikolata.',
    muzik_his: 'Jazz, Blues.',
    mevsim: 'Kış',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 duble', ideal: '2 duble', limit_ustu: '3+ duble', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Efe 5 Yıllık'], fiyat_araligi: '1100 - 1500', nereden_alinir: 'Büyük tekeller.', pop_kultur: 'Purocuların favori rakısı.', yanlis_bilinenler: 'İçinde viski olduğu sanılır, tamamen meşe fıçı etkisidir.', sozler: '"Meşenin sabrı."'
  },
  {
    id: 'tekirdag-mese',
    name: 'Tekirdağ Meşe',
    emoji: '🪵',
    color: '#d9b36c',
    aliases: ['Altın Seri Meşe', 'Tekirdağ Reserve'],
    origin: 'Türkiye',
    ana_tur: 'rakı',
    alt_tur: 'meşe_fıçı',
    gorunum: 'sarımtırak',
    olgunlasma: 'fıçılanmış',
    aroma: ['anasonlu', 'baharatlı', 'kavrulmuş'],
    alkol_seviye: 'sert',
    lore_short: 'Meşe fıçı dinlendirmesinin Tekirdağ ustalığıyla buluşması. Altın sarısı rengi, zengin baharat profili ve ağırbaşlı karakteriyle tam bir "digestif" rakı.',
    lore_full: [
      { baslik: 'Köken', metin: 'Tekirdağ sumasının meşe fıçılarda bekletilmesiyle elde edilen, Efe Meşe\\'ye rakip olarak doğmuş premium bir fıçı rakısıdır.' },
      { baslik: 'Yayılma', metin: 'Lüks restoranlarda ve et lokantalarında (steakhouse) rakı alternatifi olarak sunulur.' },
      { baslik: 'Kültürel Etki', metin: 'Rakı gastronomisini mezelerden ağır etlere doğru kaydıran ürünlerden biridir.' },
      { baslik: 'Modern Dönem', metin: 'Koleksiyonluk şişe tasarımlarıyla lüks algısını pekiştirmiştir.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Viski severlere "bizim de böyle bir lezzetimiz var" demek için ikram edilir.' }
    ],
    hammadde: 'Trakya suması, meşe fıçı, anason.',
    uretim_sureci: 'Meşe fıçılarda uzun süre dinlendirme.',
    dinlendirme: 'Meşe fıçı.',
    renk: 'Kehribar/Altın sarısı.',
    koku: 'Yoğun meşe, kavrulmuş fındık, tarçın ve geride anason.',
    tat: 'Kompleks, tam gövdeli. Anasonun tatlılığı ile meşenin kuruluğu mükemmel dengelenir.',
    finish: 'Çok zengin, odunsu ve uzun.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Viski veya Konyak kadehi', sicaklik: 'Oda sıcaklığı veya tek buz', miktar: '40 ml', hazirlik: 'Yudum yudum içilir.' },
    mix_detay: [ { isim: 'Meşe & Et', malzemeler: ['Rakı', 'Buz'], hazirlanis: 'Sek ve buzlu', neden: 'Meşe derinliği su ile zayıflatılmamalı.', ortam: 'Steakhouse, et yemeği.' } ],
    yiyecek: 'Steak, füme etler, eski kaşar.',
    muzik_his: 'Klasik Müzik, Caz.',
    mevsim: 'Kış',
    abv_range: '45',
    standart_porsiyon: '40',
    kafa_dozu: { hafif: '1 duble', ideal: '2 duble', limit_ustu: '3+ duble', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Orta', baslangic_onerileri: ['-'], orta_seviye: ['-'], premium: ['Tekirdağ No:10'], fiyat_araligi: '1300 - 1800', nereden_alinir: 'Premium mağazalar.', pop_kultur: 'Hediye olarak en çok alınan rakılardandır.', yanlis_bilinenler: 'Bozuk veya eski olduğu için sarardığı esprisi yapılır.', sozler: '"Zamanın altın rengi."'
  }`;

let content = fs.readFileSync('src/data/raki.js', 'utf-8');
content = content.replace(/\n\];/, `,\n${extraRakis}\n];`);
fs.writeFileSync('src/data/raki.js', content);
console.log("8 Rakis added.");
