const fs = require('fs');

const extraSarap = `  {
    id: 'bagcilar-misket',
    name: 'Bağcılar Misket',
    emoji: '🥂',
    color: '#fffae6',
    aliases: ['Bornova Misketi', 'Misket'],
    origin: 'Türkiye',
    ana_tur: 'şarap',
    alt_tur: 'beyaz_yerli',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['çiçeksi', 'meyvemsi'],
    alkol_seviye: 'hafif',
    lore_short: 'Ege\\'nin parfüm şişesi. Bornova Misketi üzümünden yapılan, buram buram ıtır, gül ve narenciye kokan, tatlımsı ama sek bir beyaz şarap.',
    lore_full: [
      { baslik: 'Köken', metin: 'Dünyadaki Muscat üzüm ailesinin Anadolu\\'daki en önemli temsilcisidir. İzmir Bornova kökenlidir.' },
      { baslik: 'Yayılma', metin: 'Özellikle yazlık bölgelerde sek beyaz şarap severlerin favorisi haline gelmiştir.' },
      { baslik: 'Kültürel Etki', metin: 'Kokusu o kadar tatlı ve çiçeksidir ki, içildiğinde sek (şekersiz) olması insanı şaşırtır.' },
      { baslik: 'Modern Dönem', metin: 'Türk şarapçılığının "aromatik beyaz" kategorisindeki en güçlü silahıdır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Ege sofralarının, özellikle zeytinyağlı yemeklerin vazgeçilmezidir.' }
    ],
    hammadde: '%100 Bornova Misketi üzümü.',
    uretim_sureci: 'Düşük ısıda yavaş fermantasyon, aromaların korunması hedeflenir.',
    dinlendirme: 'Çelik tank (Meşeye girmez).',
    renk: 'Açık, soluk sarı.',
    koku: 'Yoğun çiçek, hanımeli, ıtır, gül yaprağı ve limon kabuğu.',
    tat: 'Meyvemsi, canlı asidite, narenciye ve şeftali notaları.',
    finish: 'Kısa ama çok ferahlatıcı.',
    vucut: 'Light body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Beyaz Şarap Kadehi', sicaklik: 'Soğuk (8-10°C)', miktar: '150 ml', hazirlik: 'İyi soğutulmalı.' },
    mix_detay: [],
    yiyecek: 'Sushi, baharatlı Asya yemekleri, zeytinyağlı enginar.',
    muzik_his: 'Klasik Müzik, Akustik Gitar.',
    mevsim: 'İlkbahar ve Yaz',
    abv_range: '12',
    standart_porsiyon: '150',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['Misket'], premium: ['-'], fiyat_araligi: '400 - 600', nereden_alinir: 'Şarap butikleri.', pop_kultur: 'Kör tadımlarda en kolay bilinen şaraptır.', yanlis_bilinenler: 'Çok tatlı koktuğu için tatlı şarap sanılır, sek yapılır.', sozler: '"Ege rüzgarı."'
  },
  {
    id: 'papazkarasi',
    name: 'Papazkarası',
    emoji: '🍷',
    color: '#8b1a1a',
    aliases: ['Papaskarası'],
    origin: 'Türkiye',
    ana_tur: 'şarap',
    alt_tur: 'kırmızı_yerli',
    gorunum: 'berrak',
    olgunlasma: 'fıçılanmış',
    aroma: ['baharatlı', 'kırmızı meyveler'],
    alkol_seviye: 'orta',
    lore_short: 'Trakya\\'nın unutulmuş değeri. Zarif, ince kabuklu ve yüksek asitli; Türkiye\\'nin Pinot Noir\\'ı olmaya en yakın efsanevi kırmızı üzümü.',
    lore_full: [
      { baslik: 'Köken', metin: 'Trakya ve Marmara bölgesinin en eski yerel üzümlerindendir. İsmini Ortodoks papazlarının kendi kiliselerinde yaptıkları şaraplardan aldığı söylenir.' },
      { baslik: 'Yayılma', metin: 'Geçmişte çok yaygındı ancak uluslararası üzümlerin (Cabernet vb.) popülerleşmesiyle bağları söküldü. Son yıllarda yeniden canlandırılıyor.' },
      { baslik: 'Kültürel Etki', metin: 'Ağır, tanenli şaraplar yerine zarif ve asidik şarap arayanların yerel kahramanıdır.' },
      { baslik: 'Modern Dönem', metin: 'Butik üreticilerin (özellikle Chamlija) vizyonuyla tekrar hak ettiği değere kavuşmuştur.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türk şarapçılığının "köklerine dönüş" akımının en büyük sembolüdür.' }
    ],
    hammadde: '%100 Papazkarası üzümü.',
    uretim_sureci: 'Dikkatli fermantasyon.',
    dinlendirme: 'Kısa süre eski meşe fıçılar.',
    renk: 'Açık yakut kırmızısı.',
    koku: 'Vişne, kızılcık, beyaz karabiber ve hafif toprak.',
    tat: 'Tanenleri düşük ama asiditesi çok yüksek. Canlı, baharatlı ve kırmızı meyve odaklı.',
    finish: 'Temiz, tazeleyici ve orta uzunlukta.',
    vucut: 'Light to Medium',
    rakon: 'sek',
    sek_detay: { kadeh: 'Geniş Bourgogne Kadehi', sicaklik: 'Serin (14-16°C)', miktar: '150 ml', hazirlik: 'Biraz havalandırılabilir.' },
    mix_detay: [],
    yiyecek: 'Peynir tabakları, mantarlı yemekler, ızgara somon.',
    muzik_his: 'Jazz, Nostaljik Pop.',
    mevsim: 'Sonbahar',
    abv_range: '13',
    standart_porsiyon: '150',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 1 },
    etki_hizi: 'Orta', metabolizma: 'Hızlı', baslangic_onerileri: ['-'], orta_seviye: ['Papazkarası'], premium: ['-'], fiyat_araligi: '500 - 800', nereden_alinir: 'Şarap butikleri.', pop_kultur: 'Şarap geeklerinin aradığı şişelerdendir.', yanlis_bilinenler: 'Kötü ve ucuz şarap üzümü sanılır, iyi işlendiğinde muazzam zariftir.', sozler: '"Trakya\\'nın zarif sırrı."'
  },
  {
    id: 'cabernet-sauvignon-tr',
    name: 'Cabernet Sauvignon (TR)',
    emoji: '🍷',
    color: '#4a0e17',
    aliases: ['Cab-Sauv', 'Cabernet'],
    origin: 'Türkiye',
    ana_tur: 'şarap',
    alt_tur: 'uluslararası',
    gorunum: 'opak',
    olgunlasma: 'fıçılanmış',
    aroma: ['siyah meyveler', 'meşe', 'tanenli'],
    alkol_seviye: 'orta',
    lore_short: 'Dünyanın en popüler kırmızı üzümünün Türk topraklarındaki güçlü ifadesi. Bol güneş, kalın kabuk, yoğun tanen ve yıllanmaya uygunluk.',
    lore_full: [
      { baslik: 'Köken', metin: 'Bordeaux (Fransa) kökenli bu üzüm, 1990\\'larda Türkiye\\'ye yoğun olarak dikildi. Özellikle Ege ve Güney bölgelerin güneşi onu çok sevdi.' },
      { baslik: 'Yayılma', metin: 'Boğazkere\\'ye alışık olan Türk damağı, Cabernet\\'nin gövdeli ve tanenli yapısını hemen benimsedi.' },
      { baslik: 'Kültürel Etki', metin: 'Et lokantalarında ve lüks yemeklerde "en risksiz ve havalı kırmızı şarap" siparişidir.' },
      { baslik: 'Modern Dönem', metin: 'Türkiye\\'medeki en pahalı ve koleksiyonluk şarapların birçoğu bu üzümden yapılır.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Yerel üzümlerin (Öküzgözü vb.) dünyayla entegre olması için sık sık onlarla paçallanır (blend edilir).' }
    ],
    hammadde: '%100 Cabernet Sauvignon.',
    uretim_sureci: 'Uzun maserasyon, meşe fıçıda olgunlaşma.',
    dinlendirme: 'Fransız meşesinde 12-24 ay.',
    renk: 'Derin bordo, mürdüm.',
    koku: 'Böğürtlen, karadut, yeşil biber, tütün ve meşeden gelen vanilya.',
    tat: 'Tam gövdeli, ağzı kurutan güçlü tanenler, siyah meyve konsantrasyonu.',
    finish: 'Çok uzun ve baharatlı.',
    vucut: 'Full body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Büyük Bordeaux Kadehi', sicaklik: 'Oda sıcaklığı (16-18°C)', miktar: '150 ml', hazirlik: 'İçmeden önce en az 1 saat dekante edilmeli.' },
    mix_detay: [],
    yiyecek: 'Antrikot, T-Bone steak, yıllanmış sert peynirler.',
    muzik_his: 'Klasik Müzik, Ağır Caz.',
    mevsim: 'Kış',
    abv_range: '14.5',
    standart_porsiyon: '150',
    kafa_dozu: { hafif: '1 kadeh', ideal: '2-3 kadeh', limit_ustu: '4+ kadeh', ertesi_gun: 2 },
    etki_hizi: 'Orta', metabolizma: 'Yavaş', baslangic_onerileri: ['Cabernet-Merlot Blend'], orta_seviye: ['Klasik Cabernet'], premium: ['Reserve Cabernet'], fiyat_araligi: '600 - 1500', nereden_alinir: 'Tekeller, marketler.', pop_kultur: 'Kırmızı şarap denince akla ilk gelen türdür.', yanlis_bilinenler: 'Taze taze içilebileceği sanılır; tanenleri yumuşasın diye yıllanması gerekir.', sozler: '"Şarapların kralı."'
  },
  {
    id: 'kavaklidere-cuvee',
    name: 'Kavaklıdere Cuvée (Köpüklü)',
    emoji: '🍾',
    color: '#ffffcc',
    aliases: ['Altın Köpük', 'Türk Şampanyası'],
    origin: 'Türkiye',
    ana_tur: 'şarap',
    alt_tur: 'köpüklü',
    gorunum: 'berrak',
    olgunlasma: 'dinlendirilmemiş',
    aroma: ['elma', 'narenciye', 'maya'],
    alkol_seviye: 'hafif',
    lore_short: 'Kutlamaların yerli yıldızı. Emir üzümünden gelen muazzam asidite ve ince baloncuklarla, Türkiye\\'nin en köklü şampanya alternatifi.',
    lore_full: [
      { baslik: 'Köken', metin: 'Kapadokya\\'nın Emir üzümü, yüksek asiditesi nedeniyle köpüklü şarap yapımına Türkiye\\'de en uygun üzümdür.' },
      { baslik: 'Yayılma', metin: 'Yabancı şampanya fiyatlarının çok artmasıyla Türk tüketicisi kaliteli yerli köpüklülere yöneldi.' },
      { baslik: 'Kültürel Etki', metin: 'Yılbaşı gecelerinin, düğünlerin ve şık açılışların vazgeçilmez patlayan şişesidir.' },
      { baslik: 'Modern Dönem', metin: 'Geleneksel yöntemle (şişede ikinci fermantasyon) üretilen premium serileri büyük sükse yaptı.' },
      { baslik: 'Türkiye ile İlişkisi', metin: 'Türkiye\\'de köpüklü şarap tüketimi düşük olsa da, kutlama anlarında tek alternatiftir.' }
    ],
    hammadde: 'Kapadokya Emir üzümü.',
    uretim_sureci: 'Charmat metodu veya Geleneksel Şampanya metodu ile ikinci fermantasyon.',
    dinlendirme: 'Şişede tortusuyla bekleme.',
    renk: 'Açık saman sarısı, canlı köpük.',
    koku: 'Yeşil elma, limon, bisküvi ve ekmek kabuğu (maya notası).',
    tat: 'Çok yüksek asit, ağzı temizleyen ferahlık ve ince baloncukların dokusu.',
    finish: 'Kuru, tazeleyici ve asidik.',
    vucut: 'Light body',
    rakon: 'sek',
    sek_detay: { kadeh: 'Flüt veya Lale Kadeh', sicaklik: 'Buz gibi (6-8°C)', miktar: '150 ml', hazirlik: 'Buz kovasında bekletilir.' },
    mix_detay: [],
    yiyecek: 'Havyar, istiridye, çilek, kutlama pastaları.',
    muzik_his: 'Jazz, Pop, Kutlama Marşları.',
    mevsim: 'Her mevsim',
    abv_range: '12',
    standart_porsiyon: '150',
    kafa_dozu: { hafif: '1-2 kadeh', ideal: '3-4 kadeh', limit_ustu: '5+ kadeh', ertesi_gun: 2 },
    etki_hizi: 'Çok Hızlı (Gaz, alkol emilimini hızlandırır)', metabolizma: 'Hızlı', baslangic_onerileri: ['Altın Köpük'], orta_seviye: ['-'], premium: ['Geleneksel Yöntem'], fiyat_araligi: '700 - 1200', nereden_alinir: 'Tekeller, marketler.', pop_kultur: 'Kutlama denilince patlayan şişe.', yanlis_bilinenler: 'Tüm köpüklülere Şampanya denir; oysa Şampanya sadece Fransa\\'nın o bölgesinden çıkar.', sozler: '"Patlat gitsin!"'
  }
`;

let content = fs.readFileSync('src/data/sarap.js', 'utf-8');
content = content.replace(/\n\];/, `,\n${extraSarap}\n];`);
fs.writeFileSync('src/data/sarap.js', content);
console.log("4 Sarap added.");
